### ISSUE TITLE
Punctuation is wrong with longer text 

### ISSUE THREAD

**Issue by glsf91** [pndurette/gTTS#101]
When using the following command, the translation is right:
`gtts-cli "It is sunday 18 march. Outside it is 0.6 degrees. This is a test."  -l 'en' -o /tmp/message.mp3`

It is spoken out as "zero point 6 degrees".

When using the following command, the translation is wrong:

`gtts-cli "It is sunday 18 march. Outside it is 0.6 degrees. This is a long long long long long long long long long long long  test."  -l 'en' -o /tmp/message.mp3`
 
It is spoken out as "zero 6 degrees".

I think because the text is broken in pieces by this software. Probably when it encounters a period.
When using floating numbers this is not working the right way.

When pasting long text with floating points in it in google translate, it is working as expected.

Can this be fixed?

**Comment by pndurette** [comment]
Hmm, never thought of this use case! Thanks for bringing that to my attention.
Let me see what I can do.

**Comment by pndurette** [comment]
I found a fix. Modified the punctuation tokenization for `.` and `,` to ignore the match if followed by a digit. Works nicely. It will be released in `gTTS 2.0.0` that's coming imminently.

**Comment by glsf91** [comment]
Ok, thanks.
I will wait for the next release.

**Comment by pndurette** [comment]
gTTS `2.0.0` was released and should fix this! 👍
