### ISSUE TITLE
I had some fun creating an offline word cache it could then speak from! :D Here's the code.

### ISSUE THREAD

**Issue by rocket-pig** [pndurette/gTTS#103]
https://nerdsnotes.blogspot.com/2018/03/caching-googles-tts-locally.html

Thanks for your awesome project, bomb diggity ness

**Comment by pndurette** [comment]
Ahh, I still haven't tried this! Looks pretty cool (and something I'd like to poke at in next releases. In the meantime, gTTS `2.0.0` was released! :)
