### ISSUE TITLE
Concatenative?

### ISSUE THREAD

**Issue by kenanEkici** [pndurette/gTTS#104]
Does anybody know whether gTTS uses a concatenative Text-to-Speech system or a different system in their backend? And if so, please provide a source. That would be much appreciated.

**Comment by pndurette** [comment]
`gTTS` basically leverages the text-to-speech functionality of [Google Translate](https://translate.google.com). I believe it's also the same thing that is used under the hood as most of their apps/tools that provide TTS ([Google Text-to-Speech](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en), Google Play Books).

That being said, I really don't have (and can't find) any specifics about their TTS engine such as if it's concatenative or not. It's really a blackbox for `gTTS`.

**Comment by kenanEkici** [comment]
Thanks. I am aware that they use generative systems (mainly Parallel WaveNet) under the hood of Google Assistant, but the gTTS engine indeed seems like a blackbox. Maybe I can figure it out by asking the Google customer service directly. Perhaps I can reopen the issue if I were to find anything interesting.
