### ISSUE TITLE
[ASK] How to generate mp3 from bulk of text file ?

### ISSUE THREAD

**Issue by mascatur** [pndurette/gTTS#107]
eg I have hundred of text files. Is there a simpler command than typing one by one ?

I am currently typing like these:

gtts-cli -f 1.txt -l 'en' -o 1.mp3
gtts-cli -f 2.txt -l 'en' -o 2.mp3
gtts-cli -f 3.txt -l 'en' -o 3.mp3
gtts-cli -f 4.txt -l 'en' -o 4.mp3

**Comment by pndurette** [comment]
Hi, while this is out of the scope of `gTTS`, you can do this with a simple shell script.
Untested, but something like:
```bash
for file in $(ls *.txt); do
  gtts-cli -f ${file} -l 'en' -o ${file%.txt}.mp3
done
```
Hope this helps!

**Comment by mascatur** [comment]
Thanks a lot. Its work like magic.
