### ISSUE TITLE
is gTTS can't support cantonese?

### ISSUE THREAD

**Issue by kent0014** [pndurette/gTTS#111]
I see here can support, when i 
Cmd "gtts-cli --all"
Only mainlad china zh-cn,and mainland taiwan, can't find chinese (cantonese) zh-yue

**Comment by pndurette** [comment]
Google used to have `zh-yue` but removed it for some reason. It's out of my control, unless they use another language tag for it I'm not aware of. 

You can always try language tags and tell `gtts-cli` to ignore language checking (`--nocheck`), if they work even if they're not documented, example:
```
gtts-cli "some cantonese" --lang zh-yue --nocheck --ouput zh-yue.mp3
```

The rest is out of the control of this library, unfortunately. If you find a cantonese language tag, please let me know!

**Comment by pndurette** [comment]
Closing this for now. Let me know if you find a way to use Cantonese!

**Comment by ConfitureCheung** [comment]
Hi, I know it is a bit late to make a reply. I am from HK and I speak Cantonese.
I am also frustrated of no tts package that supports Cantonese. I have been searching for an answers for days without a clue.

However, I just made a blind test by using lang="zh-tw" (Taiwan Mandarin). For sure the system will speak in Mandarin. 
But if you try to speech to text, it can recognize me saying Cantonese and output text like my colloquial speech.
It is weird for me but do try it out and see if it works for you too!

**Comment by pndurette** [comment]
@ConfitureCheung Thanks for that! I can poke some of my Cantonese speaking friends to test this out.

Or anyone here who can confirm this, let us know!

**Comment by ConfitureCheung** [comment]
dear owner, 
would it be possible a bug or mistake that cause it? because the system speak mandarin but listen cantonese is kind of strange. like the system speak french but listen english.

**Comment by ConfitureCheung** [comment]
Further to this question, I have some extra findings...First of all, apologize for my python knowledge as I only learn it by myself.

i realized that text-to-speech and speech-to-text are using different package. this is why.
for text-to-speech, it is gtts. this one has no cantonese, only mandarin. e.g. audio = gTTS(text=self.phrase, lang="zh-tw", slow=False)
for speech-to-text, it is speech recognition. this one has cantonese. e.g. audio = r.recognize_google(audio, language="zh-HK")
apologize for the confusions.
