### ISSUE TITLE
Add support for accent (pt-BR)

### ISSUE THREAD

**Issue by hericlesme** [pndurette/gTTS#112]
Some Portuguese words need accents for the intonation of pronunciation. The accented input characters are being treated as 'non-ASCII' characters

**Comment by pndurette** [comment]
Oh interesting, could you please let me know more?
How are you using gTTS? cli? module? 

If by cli if you could run and add `--debug` at the end and give me the output.
If by module, please share the code, and also the input characters are are not treated properly.

**Comment by hericlesme** [comment]
I'm using the module. Look at this.
```
# -*- coding: UTF-8 -*-

from gtts import gTTS
import os
tts = gTTS(text='Olá Mundo', lang='pt-br')
tts.save("hello.mp3")
os.system("mpg321 hello.mp3")
```

The output is like this:
```
Traceback (most recent call last):
  File "speech.py", line 6, in <module>
    tts.save("hello.mp3")
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 180, in write_to_fp
    text_parts = self._tokenize(self.text)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 149, in _tokenize
    if _len(text) <= self.GOOGLE_TTS_MAX_CHARS:
  File "/usr/local/lib/python2.7/dist-packages/gtts/utils.py", line 67, in _len
    return len(unicode(text))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

**Comment by pndurette** [comment]
Oh, are you using Python 2.7?
If so, you have to use a Unicode literal:

```diff
- tts = gTTS(text='Olá Mundo', lang='pt-br')
+ tts = gTTS(text=u'Olá Mundo', lang='pt-br')
```

**Comment by hericlesme** [comment]
Oh, Great! It worked here, thank you! I did'nt know that...
Does this work normally in python3 without a literal?

**Comment by pndurette** [comment]
Yes. Python 2 and 3 handle Unicode very differently!
There's a lot of documentation on this, it can be confusing! One reason to Python 3 whenever possible! 😋
