### ISSUE TITLE
gTTS error: saving as wav but saved as MPEG

### ISSUE THREAD

**Issue by raady07** [pndurette/gTTS#116]
Trying to convert the text to speech and save as wav file using gTTS module.

my code:

`import gTTS`
`text = "This is my text in the saving folder"`
`tts = gTTS(text)`
`tts.save('sample.wav')`

The file is saved but when I check my file info:
`$ mediainfo sample.wav`
`General`
`Complete name                            : sample.wav`
`Format                                   : MPEG Audio`
`File size                                : 15.8 KiB`
`Duration                                 : 4 s 32 ms`
`Overall bit rate mode                    : Constant`
`Overall bit rate                         : 32.0 kb/s`
`FileExtension_Invalid                    : m1a mpa1 mp1 m2a mpa2 mp2 mp3`
`Audio`
`Format                                   : MPEG Audio`
`Format version                           : Version 2` 
`Format profile                           : Layer 3` 
`Duration                                 : 4 s 32 ms` 
`Bit rate mode                            : Constant`
`Bit rate                                 : 32.0 kb/s`
`Channel(s)                               : 1 channel`
`Sampling rate                            : 24.0 kHz`
`Compression mode                         : Lossy`
`Stream size                              : 15.8 KiB (100%)`

why I am getting different saved format ?

**Comment by pndurette** [comment]
The Google Translate Text-to-Speech API returns `mp3`. You can't choose the format. You can however transform it to `wav` after if you'd like, using a 3rd-party library or command.
