### ISSUE TITLE
detect python3 in the gtts-cli wrapper script

### ISSUE THREAD

**Issue by nullr0ute** [pndurette/gTTS#118]
The gtts-cli.py script runs fine with the python3 bindings but the gtts-cli assumes the python binary is called python where it's often called python3 so will fail to run properly where the environment doesn't have a plain "python"

**Comment by pndurette** [comment]
Are you using `2.0.0`? The `.py` wrapper was removed in favour of pure setuptools, winch should be handling this automatically.

**Comment by nullr0ute** [comment]
I thought I had, but it seems I was still on 1.2.2, will try it shortly, looks to be some issue with bs4 so I'm just poking to see why that is. Thanks

**Comment by pndurette** [comment]
Ah let me know!
