### ISSUE TITLE
long text cause unwanted breaks in text

### ISSUE THREAD

**Issue by guirem** [pndurette/gTTS#119]
When using long text (675 characters in french in my case), the genereted mp3 file add several breaks in middle of sentences (always at the same location if generated several times). 
There is no ponctuation at these location.
It seems there is no constant time between pauses but they get closer toward the end of text.
First 2 pauses around 190 characteres then decrease.

**Comment by pndurette** [comment]
Hi, thanks for this. 
So the Google Translate text-to-speech API only taxes a maximum of 100 characters. That’s something I have no control on. 

So what gTTS does is try to cut text where speech would pause, such as certain marks of punctuations. If there’s no punctuation in a 100 character span, it will have no choice but to cut on whitespace.

This is most likely what’s happening.
You can add `-- debug` to `gtts-cli` to see where gTTS cuts text. 

The best way to fix this is add some punctuation like a comma. If you really can’t, there’s always a way to change or add the tokenizer (if you use the library, see docs), but that’s a little more work. 

I’m going to make a note to add the 100 characters to the documentation, however. I realized it isn’t.
