### ISSUE TITLE
how to integrate my own google authorization key to this

### ISSUE THREAD

**Issue by PasinduDineth** [pndurette/gTTS#127]
Hi. i am having a issue. i need to add my own google authorization key or the json file they provide , with this library. Everything is working fine. But i need to add y own key, which i purchased from google. Thank you!

**Comment by pndurette** [comment]
This library (currently) uses the Google _Translate_ TTS, which is an open endpoint that doesn't require a key (but also doesn't provide much control). Which is totally different. You're probably looking for something like: https://github.com/GoogleCloudPlatform/google-cloud-python
