### ISSUE TITLE
404 error when q payload is empty

### ISSUE THREAD

**Issue by bjarkt** [pndurette/gTTS#128]
404 Client Error: Not Found for url: https://translate.google.com/translate_tts?ie=UTF-8&q=&tl=en&ttsspeed=1&total=120&idx=94&client=tw-ob&textlen=0&tk=311436.179921

the q argument is empty, so it returns 404, which crashes the program. Is it possible to skip the part of the text, when q is empty?

**Comment by pndurette** [comment]
Do you mind telling me how you got into this situation?  Empty parts should technically be filtered out by`utils._clean_tokens()`, so I'm quite curious which sort of edge case can this be! If you used the `cli`, please re-run with `--debug` and let me know the output. Thanks!

**Comment by bjarkt** [comment]
using these two lines:
```python
tts = gTTS(text, lang="da")
tts.save(path_to_file)
```
where `text` is this: https://pastebin.com/6rncmytD

The payload looks like this: {'ie': 'UTF-8', 'q': 'hvor vi lægger til for natten', 'tl': 'da', 'ttsspeed': 1, 'total': 120, 'idx': 93, 'client': 'tw-ob', 'textlen': 29, 'tk': '828574.711414'}
on the iteration before the crash happens, if that is any help, and idx is 94.

**Comment by pndurette** [comment]
Oh, by the way. Are you running the latest version of gTTS?

**Comment by bjarkt** [comment]
Yep, running version 2.0.1

**Comment by pndurette** [comment]
Sorry for the long delays. Will have to take a look at this!

**Comment by pndurette** [comment]
Closing as this doesn't seem to be an issue anymore.
