### ISSUE TITLE
Soundfiles without sound (or with less sound)

### ISSUE THREAD

**Issue by mthewissen** [pndurette/gTTS#13]
The following consistently results in an mp3-file without sound (0 seconds):

    from gtts import gTTS
    tts = gTTS(text='你', lang='zh')
    tts.save("ni3.mp3")

Sometimes all words result in such empty file, but I assume that happens when the tts service is not available. But even when it works for some words, '你' is one of the counterexamples that never result in a proper mp3-file.
From the around 10 words I used to test, I also noticed that the saved sound from '睡覺' is always a little bit shorter than the actual audio.

**Comment by pndurette** [comment]
Closing this as it seems the latest updates fixed this. The examples above (using an Unicode string) seem to work fine.
