### ISSUE TITLE
Bad Handshake in gTTS

### ISSUE THREAD

**Issue by LordTyrion123** [pndurette/gTTS#131]
I've been using gTTS for some basic text-to-speech for the past dew months and it has been working fine. But for the past week or so, I've been getting this error. The gTTS fails to convert the text. However, the following error appears to be randomly appearing. I reboot the RPI and the error disappears, and the gTTS starts working fine. Any idea on why this occurs? Is it just a network problem?

 gtts.tts.gTTSError: Connection error during token calculation: ("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",)

**Comment by pndurette** [comment]
> Is it just a network problem?

More specifically an SSL problem for some reason. Also this is happening at the Boudewijn26/gTTS-token level, I just do the error checking as gTTS-token doesn’t.

**Comment by LordTyrion123** [comment]
That makes sense. So, is there no way to fix it then?

**Comment by pndurette** [comment]
#132 also seems to have this issue. Will have to look it it. @Boudewijn26?

**Comment by pndurette** [comment]
@Boudewijn26 No worries! I was just wondering if you got pinged about SSL handshake errors too (I've noticed a few projects use gTTS-Token on its own). Thanks for that link. Will have a look and experiment when I get time myself (enjoy your holiday!).
