### ISSUE TITLE
runtime error with example code

### ISSUE THREAD

**Issue by juergmaier** [pndurette/gTTS#134]
I am using python 3.6 64 bit on windows 10

my code:
1 from gtts import gTTS
2 tts = gTTS('please')

on line 2 I get "RuntimeError: dictionary changed size during iteration"

**Comment by pndurette** [comment]
Sorry for the delay, have you figured it out?

**Comment by juergmaier** [comment]
did not investigate because I just gave it a try and then did other stuff.
