### ISSUE TITLE
Adjust Tokenizer

### ISSUE THREAD

**Issue by jhoelzl** [pndurette/gTTS#135]
Hello, very often the gTTS Speech Synthesis does not spell the current time correctly since the tokenizer splits it. Example: 
> ... the current time is 08:30 o'clock.

The text is it is split on ":"
Is there a possibility to prevent a split on ":" in general?
Thanks!

**Comment by jhoelzl** [comment]
I could solve it like hits:

```python
from gtts import gTTS
from gtts import tokenizer
from gtts.tokenizer import tokenizer_cases

tts = gTTS("My text", "en", tokenizer_func=tokenizer.core.Tokenizer([
            tokenizer_cases.tone_marks,
            tokenizer_cases.period_comma,
            # tokenizer_cases.other_punctuation  # do not use it otherwise times are split: e.g. 10:04
            ]).run)


```

**Comment by pndurette** [comment]
Actually, let me reopen this. This is a valid tokenizer case that should be added: time notation. Thanks for this.

**Comment by jhoelzl** [comment]
Thanks!
