### ISSUE TITLE
Wavenet voices

### ISSUE THREAD

**Issue by nesrad** [pndurette/gTTS#136]
Any plans to support new Wavenet voices?

**Comment by pndurette** [comment]
This lib uses purely the TTS from `translate.google.com`, but It's in my plans to actually allow to use the actual Google Cloud Text-to-Speech API since it could very well be adapted, I believe (and be more legit/production ready).

**Comment by Tobe-Continued** [comment]
nope :) https://cloud.google.com/text-to-speech/

**Comment by Tobe-Continued** [comment]
wavenet is for tts too
