### ISSUE TITLE
Gtts can not work offline ?

### ISSUE THREAD

**Issue by hanzalakhan625** [pndurette/gTTS#139]
It says that the urllib error.

**Comment by lalittech** [comment]
No it is not offline.As it requires to request to an public open endpoint.

**Comment by jhoelzl** [comment]
@hanzalakhan625, you can make an own "workaround" to use it offline. When you have phrases that are every time the same, save the generated wav file as a cache file (e.g. by using the combination of text and language code as a hash for the filename).

Afterwards, when requesting the TTS, first have a look if a cache file already exists and play it, when not continue to use the online gTTS.

**Comment by pndurette** [comment]
Caching would be useful, especially for the apps that can often repeat the same stuff.
