### ISSUE TITLE
Gtts for production use case limatation 

### ISSUE THREAD

**Issue by lalittech** [pndurette/gTTS#141]
Can we use this python(Gtts API) for production use. If so what are the limitations with using GTTS.

**Comment by pndurette** [comment]
I would not recommend it. It's uses an undocumented API that Google can pull the plug on at any time. I would suggest going with (paid) cloud TTS solutions like Google Cloud Text-to-Speech API or Amazon AWS Polly (or other solutions, really). 

I would actually like to support something like Google Cloud TTS (letting users provide their API key). But that's not coming soon.
