### ISSUE TITLE
gTTS Issue 

### ISSUE THREAD

**Issue by SheikhMAaqib** [pndurette/gTTS#142]
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gtts import gTTS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gtts.py", line 19, in <module>
    myobj = gtts(text=mytext, lang=language, slow=False) 
TypeError: 'module' object is not callable
>>> 
KeyboardInterrupt

This is the problem how to solve this

**Comment by pndurette** [comment]
Hi! I'm missing a bit of context here. Looks like you're sending the output of the `python` interpreter but I'm confused as its referencing to some of your code (which is missing). Mind sharing `gtts.py` (where the error on line 19 happens)?
