### ISSUE TITLE
Custom language

### ISSUE THREAD

**Issue by manuelblancovalentin** [pndurette/gTTS#146]
I think this question should probably be redirected somewhere else (to google speech developers maybe) but as I'm totally lost here I'd love if you guys could help me figure out if what I'm trying to achieve is even feasible.

Would it be possible to implement a custom language and use it in gTTS? Say I'd like to implement indoEuropean or medieval English language or any other language that's not on the default google recognizable languages list. Would that be possible? 

If yes, does anyone know which would be the steps to follow to achieve that?

Thanks in advance!

**Comment by DieKatzchen** [comment]
That would involve a lot of work that lies way outside the scope of this repo. Your two options are to ask the Google Speech developers to pretty please develop it for you, or get your hands dirty with something like Festival. It won't sound as good because Festival is older tech, but it's a good place to start.

**Comment by DieKatzchen** [comment]
Doing a bit more research, if you want a neural network based speech synthesis like the Google one, I'd look into Tacotron. It's a Tensorflow based speech synthesis engine. It'll take a pretty large sample to train it though, and if you're trying to train it in a more obscure language that might be quite the hurdle. I think Tacotron was trained with audiobooks.

**Comment by pndurette** [comment]
As @DieKatzchen, this is beyond this scope. All this library is doing is letting you download an mp3 that’s normally generated by a website. 

Cool stuff about Tacotron though!
