### ISSUE TITLE
 When sending multiple requests in succession, it doesn't work

### ISSUE THREAD

**Issue by XueWei** [pndurette/gTTS#147]
My version:
gTTS==1.2.1
gTTS-token==1.1.2

When I tried to generate speech for a long article, the request is sent in succession. Then I got the error after a couple of sentences:
'NoneType' object has no attribute 'group'

Is this token error message? Any limitation for the new token? Any workaround for this issue?

**Comment by pndurette** [comment]
I’d say this is related to #151, and has been fixed.
