### ISSUE TITLE
pip3 installs gTTS as UNKNOWN

### ISSUE THREAD

**Issue by maximelacroix** [pndurette/gTTS#159]
Installation fails on raspberry Pi by using pip or pip3.    

pi@raspberrypi:~ $ sudo pip3 install gTTS
Downloading/unpacking gTTS
  Downloading gTTS-2.0.2.tar.gz
  Running setup.py (path:/tmp/pip-build-8qau96xw/gTTS/setup.py) egg_info for package gTTS
    
    warning: no files found matching 'README.rst'
Installing collected packages: gTTS
  Running setup.py install for gTTS
    
    warning: no files found matching 'README.rst'
Successfully installed gTTS
Cleaning up...

pi@raspberrypi:~ $ sudo pip3 list
[...]
UNKNOWN (2.0.2)

**Comment by pndurette** [comment]
gTTS v2.0.3 fixes the `warning: no files found matching 'README.rst'` issue. Let me know if that fixes your problem too.

**Comment by maximelacroix** [comment]
@pndurette I confirm there is no more warning (tx!) but it still does install the package as UNKNOWN (2.0.3) for both pip and pip3...  :-(

**Comment by pndurette** [comment]
@maximelacroix Ah! Check #158, someone had this issue, and there's a fix.

**Comment by maximelacroix** [comment]
@pndurette This fix does not work raspbian (or I don't know how to make it work).

I tried:
 cd /usr/local/lib/python3.4/dist-packages/
sudo mv UNKNOWN-2.0.3.egg-info/ gTTS-2.0.3.egg-info/
 pip3 install --user --force-reinstall --ignore-installed --no-binary :all: gTTS
Usage:   
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-binary

Then tried removing --no-binary:  

sudo pip3 install --user --force-reinstall --ignore-installed :all: gTTS
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 269, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2708, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', ':all:')

Storing debug log for failure in /root/.pip/pip.log

**Comment by maximelacroix** [comment]
Ok upgrading setuptools solved this issue:
pip install setuptools --upgrade

**Comment by pndurette** [comment]
Nice! Good to know. My next comment would have been that I see this is Python 3.4 which is getting old in the 3.x series. `2.0.2` modernized the setup, so I see its dropping support for older ways.
I'm suspecting more recent 3.x would have an updated `setuptools`. Glad you fixed it!

**Comment by kalisetti** [comment]
> Ok upgrading setuptools solved this issue:
> pip install setuptools --upgrade

This worked for me. Thankyou
