### ISSUE TITLE
ImportError: cannot import name 'gtts_token'

### ISSUE THREAD

**Issue by herobrine1346** [pndurette/gTTS#165]
![49007493_220612872185096_6626514597853528064_n](https://user-images.githubusercontent.com/28768982/50501293-14160080-0a92-11e9-89e5-e78e01da32b1.png)

**Comment by pndurette** [comment]
Hmm, hard to say. I see Python 3.6. Raspberry Pi, hmm. Mind sharing your `tts.py`?

**Comment by herobrine1346** [comment]
`
# -*- coding: utf-8 -*-
import os
from os import path
from gtts import gTTS

zh = "zh-TW";
msg = '語音測試 test'

tts = gTTS(msg, lang=zh)
tts.save('tts.mp3')
os.system('tts.mp3')
`

**Comment by pndurette** [comment]
Hmm, I ran your code—with the follow changes to make it work—
```diff
# -*- coding: utf-8 -*-
import os
from os import path
from gtts import gTTS

-zh = "zh-TW";
+zh = "zh-TW"
msg = '語音測試 test'

tts = gTTS(msg, lang=zh)
tts.save('tts.mp3')
-os.system('tts.mp3')
+#os.system('tts.mp3')
```
And it runs fine. I suspect there's something broken with your particular Python install. I can't think of anything else at the moment..

**Comment by herobrine1346** [comment]
It works fine on windows 10,
I just don't know why the Raspberry Pi has been showing this error all the time.

**Comment by pndurette** [comment]
I'm not familiar enough with the specifics of Python on Raspberry Pi operating systems. I don't know if that's a thing that people do on Pis, but maybe in a clean virtualenv with a recent Python?
