### ISSUE TITLE
Installation runs but doesn't install

### ISSUE THREAD

**Issue by user2684** [pndurette/gTTS#169]
Hi, I'm running python 2.7 on raspbian and I have an issue while installing with pip. Installation gives no error but looks like nothing has been installed, neither the cli nor the python module. 
Same behaviour with 2.0.3 and 2.0.2. No issues instead with 2.0.1. gtts-token is already installed.
```
root@60d870ce88bd:/# pip install gtts
Downloading/unpacking gtts
  Downloading gTTS-2.0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-mmmNCr/gtts/setup.py) egg_info for package gtts
    
Installing collected packages: gtts
  Running setup.py install for gtts
    
Successfully installed gtts
Cleaning up...
root@60d870ce88bd:/# which gtts-cli
root@60d870ce88bd:/# python
Python 2.7.9 (default, Sep 26 2018, 05:58:52) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gtts import gTTS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gtts
```
Thanks!

**Comment by pndurette** [comment]
Hmm. `gTTS` `2.0.2` modernized the setup. Try upgrading your `setuptools` maybe:
```
pip install setuptools --upgrade
```
Although it prob. wouldn't even install. But this is Python 2.7 so who knows. Let me know if this helps with the issue. Is it in `pip list`?

**Comment by pndurette** [comment]
Sweet!
