### ISSUE TITLE
ValueError: Unable to find token seed

### ISSUE THREAD

**Issue by mdiller** [pndurette/gTTS#176]
Hey, I've been using the library for a while now and I appreciate all the work that has gone into it. Has anyone run into and exception that looks like this before?

```
File '/usr/local/lib/python3.6/site-packages/gtts/tts.py', line 247, in save
    self.write_to_fp(f)
  File '/usr/local/lib/python3.6/site-packages/gtts/tts.py', line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File '/usr/local/lib/python3.6/site-packages/gtts_token/gtts_token.py', line 28, in calculate_token
    seed = self._get_token_key()
  File '/usr/local/lib/python3.6/site-packages/gtts_token/gtts_token.py', line 59, in _get_token_key
    'Unable to find token seed! Did https://translate.google.com change?'
ValueError: Unable to find token seed! Did https://translate.google.com change?
```

Its happening on one computer and not another one, and I have the same versions of gtts and gtts-token (shown below) so I'm wondering if maybe my IP got blacklisted or something?
```
gTTS: 2.0.3
gTTS-token: 1.1.3
```

**Comment by pndurette** [comment]
Sorry for the (crazy) response delay, but it could have been a transient issue, unless your two computers really have different external IPs, then what you suggested is also a possibility.

**Comment by FurkanThePythoneer** [comment]
ç

**Comment by DanielKoohmarey** [comment]
I'll add I encountered this same error in 2020 and solved it by adding a try/catch for a ValueError around my gTTS call and wrapping it with a while loop that ran until it successfully worked. Seems to be a temporal issue.
