### ISSUE TITLE
Win7 playing a file second time around

### ISSUE THREAD

**Issue by Audio-Rochey** [pndurette/gTTS#177]
I have this code running in a loop:  
```
str4 = "PID" + str3 + "Updated"
tts = gTTS(text=str4, lang='en')
tts.save('PIDUPDATED.mp3')
playsound('PIDUPDATED.mp3')
```

and it works fine the first time through the loop.
The second time, I get an exception.

I added a small print function to see where it was failing, and it looks like tt.save is causing the issue.

I'm a terrible programmer (I'm a HW EE), but I'm out of ideas here.

**Comment by bghanchi** [comment]
Can you show your error?
