### ISSUE TITLE
About google account & voices

### ISSUE THREAD

**Issue by wuyechang** [pndurette/gTTS#178]
Because this is a library using Google Text-to-Speech API, I have two questions.
1. Given that Google TTS API is not free, why can I use this library without specifying a Google account? Billing is not needed?
2. There are some languages and voices not listed in Google TTS API documentation, like Armenian & Bangali, etc., while I can use them with gTTS. Why?

**Comment by pndurette** [comment]
Hi @wuyechang!

1. You're correct: this is using an undocumented endpoint used by the Google Translate, so it's not directly using any Google Cloud services (but I'd like to make it be able to if you've got an API key!)

2. Again, we're limited by Google Translate, so the languages we can do are the ones they've allowed there, with very little extra control, unfortunately.
