### ISSUE TITLE
About speech recognition

### ISSUE THREAD

**Issue by homink** [pndurette/gTTS#180]
Hi,

I just found this repo and have got very impressive. Amazing work done.

Also I wonder if there is any possibility that interfaces with speech recognition because the Google translate web page allows the speech recognition as well.

Best,
Homin

**Comment by pndurette** [comment]
Hi @homink, _so_ sorry I just got to this! Thank you very much! 

As for speech recognition, that got me interested. I was looking at how it works, and first of all, it only works in Chrome (and Firefox as this author [writes](https://codeburst.io/html5-speech-recognition-api-670846a50e92)) as it leverages the [Web Speech API
](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API). From what I understand, it leverages the browser itself. Something interesting I want to look into (but that not be possible on the command-line outside of bringing up a headless browser or something)
