### ISSUE TITLE
Hangs on setup.py ?

### ISSUE THREAD

**Issue by metal3d** [pndurette/gTTS#181]
Hello.

I'm trying to install mycroft wich requires gTTS 2.0.3.

Because it hangs on gTTS installation, I tried on my own virtualenv to install gTTS.

```
cd /tmp
python3 -mvenv vvv
source vvv/bin/activate
pip3 install --upgrade pip setuptools
pip3 install -v gTTS
```
Then it hangs on:
```
  Added gTTS from https://files.pythonhosted.org/packages/e6/37/f55346a736278f0eb0ae9f7edee1a61028735ef0010db68a2e6fcd0ece56/gTTS-2.0.3.tar.gz#sha256=a6d4cf039da2797de8af2da7c1f0ce700ac0b48601ce6c11a02b337fd6bdcf57 to build tracker '/tmp/pip-req-tracker-lviykjnm'
    Running setup.py (path:/tmp/pip-install-bgmr_cuv/gTTS/setup.py) egg_info for package gTTS
    Running command python setup.py egg_info
``` 

I tried to remove cache, to update or not pip, setuptools, and so on. Nothing works.

The process that is hanging is:
```
/tmp/vvv/bin/python3 -c import setuptools, tokenize;__file__='/tmp/pip-install-bgmr_cuv/gTTS/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')) egg_info --egg-base pip-egg-info
```

I'm on Fedora 30, using python 3.7.3

**Comment by metal3d** [comment]
Note: I also tried to remove pip cache, no changes

**Comment by metal3d** [comment]
I downloaded the package:
```
pip3 download gTTS
```

And removed `setup_requirements`. It seems to compile now. Can you give any explanation about the fact that it hangs for that package and not others ?

One other thing, why to not provide wheel package ?

**Comment by pndurette** [comment]
> One other thing, why to not provide wheel package ?
That's a very good question. I'll add this to things to add. It would really help a lot of setup issues people have.

**Comment by pndurette** [comment]
As of `v2.0.4`, `gTTS` is now build as a wheel package, which should simplify a lot of installs!

**Comment by dbarrundiag** [comment]
Hi @metal3d thank you so much for this post. I am having the same issue with
`pip install avro-python3==1.10.0 -v`

it hangs on:
```
Running setup.py (path:/tmp/pip-install-bml_h_18/avro-python3/setup.py) egg_info for package avro-python3
Running command python setup.py egg_info
```

any chance you can share how you went about solving this?

Thank you so much!
