### ISSUE TITLE
Seems some language codes arent working?

### ISSUE THREAD

**Issue by projectlance** [pndurette/gTTS#182]
Greetings,

Seems some languages other than english arent working. Tried using language codes right here https://cloud.google.com/speech-to-text/docs/languages

some work, like en-us and en-gb but other languages such as it-it, or fil-ph arent supported anymore?

`Traceback (most recent call last):
  File "tts.py", line 14, in <module>
    tts = gTTS(text=message, lang=language, slow=False)
  File "C:\Python37-32\lib\site-packages\gtts\tts.py", line 121, in __init__
    raise ValueError("Language not supported: %s" % lang)
ValueError: Language not supported: fil-ph`

using gtts version 2.0.3 btw.

**Comment by pndurette** [comment]
Oh! The API documented on the link you provided isn’t the same. The Google Translate languages don’t match 1:1 the Google Cloud TTS service. To see which languages are available to you, try `gtts-cli --all` or via the `gtts.lang` module.
