### ISSUE TITLE
gtts-cli not recognizing own commands

### ISSUE THREAD

**Issue by LWFlouisa** [pndurette/gTTS#183]
Whenever I type this: ```gtts-cli 'hello' --output hello.mp3```

It reads as if it doesn't even recognize the command. I downloaded, as I'm trying to learn how to do speech to text, not text to speech.

I get this error instead:

```
usage: gtts-cli [-h] [-f FILE] [-o DESTINATION] [-l LANG] [--slow] [--debug]
                [text]
gtts-cli: error: unrecognized arguments: --output hello.mp
```

It just treats it as if I only typed gtts-cli. Even in the times it works, it only line breaks, and goes to this in terminal:

```
>>
```

**Comment by pndurette** [comment]
@LWFlouisa Sorry to reply to this so late, my bad. Did you ever figure it out? I can't replicate this with the latest version (running on Python 3.7).

**Comment by LWFlouisa** [comment]
I can check it out and see, and then follow up on it!
