### ISSUE TITLE
Citing this repository in an academic article

### ISSUE THREAD

**Issue by KatyaTulit** [pndurette/gTTS#184]
I used this repo to create stimuli for my psycholinguistic experiment and I would like to cite it in my academic article. Do you have any standard way of doing it?
Maybe you have a Zenodo DOI for it? [https://help.github.com/en/articles/referencing-and-citing-content](url)

**Comment by pndurette** [comment]
Sorry I took so long to get back to you on this—
I initially looked it up but this is def. not something I have. Did you eventually figure it out?
