### ISSUE TITLE
Direct output in python

### ISSUE THREAD

**Issue by jbrepogmailcom** [pndurette/gTTS#192]
Hello! Seems the issue 26 did not offer generic solution and yet it has been closed. Pygame does not install on my OrangePi Zero, so I can not play in python from file-like object. Or is there any other solution?

I would like to repeat question again. In the examples, the sound retrieved is inserted into file-like python object, yet there is no solution described how to play that object in python. The only solution recommended is through library pygame that requires tons of other installations (SDL, FONT, IMAGE, MIXER, PNG, JPEG, SCRAP, PORTMIDI, PORTTIME, FREETYPE)

**Comment by pndurette** [comment]
Hi @jbrepogmailcom, hmm. I'm not sure how I can help. You're running on a very limited piece of hardware which I can't test on, and multimedia stuff on Linux/Python can be tricky (as you can see in all the comments and suggestions in #26!). None of the other suggestions there work?

**Comment by jbrepogmailcom** [comment]
I went through pain of installing pygame and it does not work. I have to stick with calling os.system("play....
But there is one problem, in python calling play, it looses about 1 sec at beginning of mp3, second os.system("play does not have that problem, so I had to create empty mp3 and I have to call os.system("play several times. Not very elegant solution. Would you know how to get rid off of the 1sec play initialization?

**Comment by pndurette** [comment]
Maybe someone else can chime in, but this goes beyond what I have experience with, sorry. I couldn't say.

**Comment by ap-ple** [comment]
I'm trying to find a way to `def`ine a `speak(text, lang = 'en')` function that would simply take the `text` and `lang` parameters to save a spoken block of text to a temporary file and play it. I would also like to be able to reuse the `speak` function.
```
from gtts import gTTS
from tempfile import TemporaryFile
tts = gTTS(text='Hello', lang='en')
f = TemporaryFile()
tts.write_to_fp(f)
# Play f
f.close()
```
What is the simplest way to replace `# Play f` here?

**Comment by themdrizwanansari** [comment]
@ap-ple This solution worked for me with playsound!
I don't feel significant decrease in speech output  delay though.
I guess much of the delay is in processing by gTTS
