### ISSUE TITLE
Problem with ascii/utf-8 still persists in cli ver. 2.0.4

### ISSUE THREAD

**Issue by jbrepogmailcom** [pndurette/gTTS#193]
gtts-cli -l cs 'Ahoj, jak se máš?' | play -t mp3 - -
Usage: gtts-cli [OPTIONS] <text>

Error: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
play FAIL formats: can't open input  `-':

**Comment by pndurette** [comment]
@jbrepogmailcom Oh no! I haven't seen this one in forever. Let me investigate.
One thing I can suggest right sway though, is to use Python 3 if possible! That will fix it.

**Comment by pndurette** [comment]
Hi @jbrepogmailcom, could you tell me what you're running this on? I was unable to reproduce on Python 2.7(.16) (where this would have likely happened) or Python 3.7.
