### ISSUE TITLE
Delay in response time

### ISSUE THREAD

**Issue by sophjoe** [pndurette/gTTS#194]
Hi,
Below is my program. And when i try run the program, the response time is after 2 seconds. How can i make the response time faster. As when we use google assistant it responds within a fraction of seconds. Pls suggest how to make the response time faster. Thanks in advance

                    def speak(audioString):
                        global num
                        num += 1
                        print(audioString)
                        toSpeak = gTTS(text=audioString, lang='en', slow=False)
                        # tts = gTTS(text=audioString, lang='en')
                        # tts.save("audio.mp3")
                        file = str(num) + ".mp3"
                        toSpeak.save(file)
                        # os.system("mpg321 audio.mp3")
                        playsound.playsound(file, True)
                        os.remove(file)

                    def recordAudio():
                         r = sr.Recognizer()
                       

                        with sr.Microphone() as source:
                            r.adjust_for_ambient_noise(source, duration=0.2)
                            print("Say something!")
                            audio = r.listen(source)

                      
                        data = ""
                        try:
                           
                            data = r.recognize_google(audio)
                            #print("You said: " + data)
                        except sr.UnknownValueError:
                            print("Google Speech Recognition could not understand audio")
                            #sys.exit()
                        except sr.RequestError as e:
                            print("Could not request results from Google Speech Recognition service; {0}".format(e))
                            #sys.exit()

                        return data

                    def diana(data):
                        if "how are you" in data:
                            speak("I am fine")
                            #sys.exit()

                        if "current time" in data:
                            speak(ctime())
                            #sys.exit()

**Comment by pndurette** [comment]
Hi @sophjoe, you could use a file-like object to play the file directly. Google Assistant uses the actually Cloud Speech API directly, which has a cost per word IIRC.

See: https://gtts.readthedocs.io/en/latest/cli.html#playing-sound-directl, but also #26!

**Comment by sophjoe** [comment]
@pndurette  Thank you
