### ISSUE TITLE
speech_recognition module error r.pause_threshold .Stuck in “Listening..."

### ISSUE THREAD

**Issue by efeay123** [pndurette/gTTS#196]
`

    import speech_recognition as sr

    r = sr.Recognizer()

    with sr.Microphone() as source:

    r.pause_threshold = 1

    print("Listening...")

    audio = r.listen(source)

    data = r.recognize_google(audio, language='tr-tr')

    print('User: ' + data )`

When I run the program, it always listens and does not respond to commands. Error in r.pause_threshold. For more information you can write

**Comment by pndurette** [comment]
Hi, perhaps you have the wrong repo to ask? I don’t see any usage of this library in your code?
