### ISSUE TITLE
TTS breaks on words ending with m.

### ISSUE THREAD

**Issue by New-asterisk** [pndurette/gTTS#197]
### Expected behaviour:
gTTS("Them.").save(tempname) returns a file pronouncing the word "them".

### Actual behaviour:
gTTS("Them.").save(tempname) returns a file pronouncing something like "the messier".

Seems to parse the last letter "m." with a dot as a title.

**Comment by nyahwhy** [comment]
https://github.com/pndurette/gTTS/blob/4f70fd4937945185fb6b145b1c6a13707e9567bb/gtts/tokenizer/symbols.py#L9

**Comment by pndurette** [comment]
So sorry for this crazy delay—
As said above, this is a known issue, I wanted to provide an example of substitution, but ended up putting one that can break things.

Add the following before initializing your `gTTS` object:
```
gtts.tokenizer.symbols.SUB_PAIRS = []
```
I will replace this with something less likely to break common speech.

**Comment by pndurette** [comment]
This has been fixed in `gTTS` `2.1.0`!
