### ISSUE TITLE
use wb+ to save speech to mp3 format

### ISSUE THREAD

**Issue by manojpawarsj12** [pndurette/gTTS#201]
wb+

Opens a file for both writing and reading in binary format. Overwrites the existing file if the file exists. If the file does not exist, creates a new file for reading and writing.

**Comment by pndurette** [comment]
Hi @manojpawarsj12!

I'm finally taking the time to go through issues, apologies!

I'm having issues understanding what this would accomplish. Considering the file opened with `wb`  in the `save` method is within a context manager, this would have no effect to anything outside of the `with` block.

The `write_to_fp()` method exists to do what you want. You can create you own file handle and set it to `wb+` if you'd like (to read and write to the same handle).
