### ISSUE TITLE
Wrong token with accentuated chars

### ISSUE THREAD

**Issue by desbma** [pndurette/gTTS#21]
Hi,

I'm the author of [google_speech](https://github.com/desbma/GoogleSpeech), a project with slightly different features, but similar goal as gTTS.
Since the recent Google `tk` change, I am using your token calculation code. I have tried myself to reverse engineer the calculation from JS code, but quickly abandoned, so congrats @Boudewijn26 :)
However if the text contains accentuated chars the token is wrong and consequently Google returns a 403.

To reproduce with gTTS:
`gtts-cli 'he'` => works fine
`gtts-cli 'hé'`=> 403 error

**Comment by Boudewijn26** [comment]
Good catch, I didn't check that. I made a pull request that fixes this. Now if I can just get Python's string handling compatible with all versions.

**Comment by pndurette** [comment]
Thanks again @Boudewijn26 & @desbma. Fixed in #22, released in `v1.1.3`
