### ISSUE TITLE
Does gTTS-cli have `auto detect language` feature?

### ISSUE THREAD

**Issue by byteshiva** [pndurette/gTTS#211]
Does `gTTS-cli` have auto detect language feature?

Say for example I pass language string other than English, Can `gtts-cli` detect the language?

Example:
```
stringLang = `தமிழக பாஜ\., தலைவராக இருந்த தமிழிசை சவுந்தரராஜன், கடந்த ஆகஸ்ட் மாதம் தெலுங்கானா கவர்னராக நியமிக்கப்பட்டார்\. அவர் தமிழக பா\.ஜ\., தலைவர் பதவியை ராஜினாமா செய்தார்\. இதனால், கடந்த மூன்று மாதங்களுக்கு மேலாக மாநில பாஜ\., தலைவர் பதவி காலியாக இருந்து வருகிறது\.`

$ gtts-cli ${stringLang} -o output.mp3

```
Will above command work?

```
"{code:'auto',name:'Detect language'}
```

**Comment by pndurette** [comment]
Hi, sorry I wanted to make sure it wasn't a bug before closing (it's supposed to explicitly remove the `{code:'auto',name:'Detect language'}` bit from the language list). So no, it won't.
