### ISSUE TITLE
Basic gTTS library usage causes RuntimeError in Python 3.7

### ISSUE THREAD

**Issue by macelux** [pndurette/gTTS#213]
I am using python 3.7, and i have successfully installed gTTS but i get this error when i run this simple code 

from gtts import gTTS
tts = gTTS('hello')

https://stackoverflow.com/questions/59888785/basic-gtts-library-usage-causes-runtimeerror-in-python-3-7

**Comment by pndurette** [comment]
Hi @macelux. Indeed looks like a bug! Will fix and add tests, mostly likely this weekend.
Thanks for asking on SO too, great response over there!

**Comment by macelux** [comment]
Ok. Will check back this weekend.

**Comment by pndurette** [comment]
@macelux, fixed in `gTTS 2.1.1`, just released! Thanks for the report.

**Comment by macelux** [comment]
`gTTS 2.1.1` isn't available on pip3 yet.

**Comment by pndurette** [comment]
@macelux It should be! 😄 
Perhaps you haven't done `--upgrade` in your pip command?
https://pypi.org/project/gTTS/

**Comment by macelux** [comment]
Still the same even after `- -upgrade`

**Comment by pndurette** [comment]
Hmm that's odd. Care to share your command and its output?

**Comment by macelux** [comment]
i did this `pip3 install --upgrade pip` and this `pip3 install gTTS` and here is the result, 
`Requirement already satisfied: gTTS in /usr/local/lib/python3.7/dist-packages (2.1.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gTTS) (1.12.0)
Requirement already satisfied: gtts-token>=1.1.3 in /home/mac/.local/lib/python3.7/site-packages (from gTTS) (1.1.3)
Requirement already satisfied: beautifulsoup4 in /home/mac/.local/lib/python3.7/site-packages (from gTTS) (4.8.2)
Requirement already satisfied: click in /home/mac/.local/lib/python3.7/site-packages (from gTTS) (7.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from gTTS) (2.21.0)
Requirement already satisfied: soupsieve>=1.2 in /home/mac/.local/lib/python3.7/site-packages (from beautifulsoup4->gTTS) (1.9.5)`

**Comment by pndurette** [comment]
Ahh I see! It's `gTTS` that needs `--upgrade` not `pip` in this case.
Try: `pip3 install --upgrade gTTS`. Should do the trick! :D

**Comment by macelux** [comment]
> Ahh I see! It's `gTTS` that needs `--upgrade` not `pip` in this case.
> Try: `pip3 install --upgrade gTTS`. Should do the trick! :D

Thanks. It worked!!
