### ISSUE TITLE
connection with pydub

### ISSUE THREAD

**Issue by jaromrax** [pndurette/gTTS#215]
Hi, gtts is very nice. 
In a case I wanted to avoid file creation, I would like to get the sample to pydub.
But I tried few combinations that do no work:
```
from pydub import AudioSegment 
sodata = BytesIO()
tts = gTTS('hello', lang='en')
tts.write_to_fp(sodata)

song = AudioSegment.from_file(  sodata , format="mp3")
# OR
# song = AudioSegment.from_file( BytesIO( sodata ), format="mp3")
song.export("out.mp3", format="mp3")
```
Any ideas? Thanks.Jaro

**Comment by goldstar611** [comment]
You need to call `sodata.seek(0)` to set the file pointer back to the beginning of the stream. Do this after you write to it but before you read from it.
