### ISSUE TITLE
ImportError: cannot import name 'gTTS' from partially initialized module 'gtts'

### ISSUE THREAD

**Issue by Edd-dev** [pndurette/gTTS#222]
Likely due to circular import

![gtts](https://user-images.githubusercontent.com/62643194/85219723-c08a2780-b395-11ea-8df1-cd7e4bd535ad.png)

**Comment by pndurette** [comment]
Ah that's because your file is named `gtts.py` so when you do `from gtts import gTTS`, Python is trying to import the file you're currently running.

Try renaming your script to something else, should work!

**Comment by Edd-dev** [comment]
Thank you it worked 😊
