### ISSUE TITLE
Why does "speed" only accept slow as argument?

### ISSUE THREAD

**Issue by londer1995** [pndurette/gTTS#224]
I was reading [the official doc.](https://buildmedia.readthedocs.org/media/pdf/gtts/latest/gtts.pdf) because I need to speed up the gTTS voice for a little project, but it seems impossible to do.

I also tried [AudioSegment](https://pypi.org/project/pydub/), but it's not affecting the voice at all, returning an error:

`'NoneType' object has no attribute '_spawn'
`

Can you add argument "fast" please? 

EDIT: I read a bunch of ppl asking for it, would it be difficult to implement?

**Comment by pndurette** [comment]
Hi @londer1995,

There’s only _slow_ because this is what the service this library wraps offers. Normal or slow (which is used to slow down translations so people can understand better). You’d have to use a sound manipulation tool to do more, like `pydub` you mentioned.

**Comment by londer1995** [comment]
pydub is working (it was a stupid mistake!), but there is some delay in the process using it. Also, sometimes the normal and fast voices speak together, forcing you to set up a time.sleep at least of 1 secs to let the whole process finish and get only the edited voice.

Thx for the fast replay tho, it makes sense. Have a nice day
