### ISSUE TITLE
No-Longer Working

### ISSUE THREAD

**Issue by Enverex** [pndurette/gTTS#226]
As of today (or a few days ago, some time recently anyway) this has stopped working and simply throws a "Error: Unable to find token seed! Did https://translate.google.com change?" error.

**Comment by pndurette** [comment]
Arg, quite possible. Will need to investigate! Thanks for the report.

**Comment by Gnome-py** [comment]
I am currently getting this error aswell

**Comment by kwmkwm** [comment]
I'm getting this error intermittently.  Sometimes it works as expected, sometimes it gives the error.

**Comment by pndurette** [comment]
Yeah, it's very intermittent.. Trying to find a way.

**Comment by alexrink96** [comment]
> Yeah, it's very intermittent.. Trying to find a way.

Hi, thanks for the gtts package, it's very useful. I noticed that using 'urlib.request' throws 403 error when trying to fetch data from 'https://translate.google.com' but 'requests' library works perfectly fine, so I managed to solve this problem saving audio using 'reqests' package. Hope it helps.

**Comment by redrussianarmy** [comment]
Hi @alexrink96 I have same problem. Where is the urlib.request located that you mentioned? Could you please provide me a guidance? Thank you.

**Comment by alexrink96** [comment]
> Hi @alexrink96 I have same problem. Where is the urlib.request located that you mentioned? Could you please provide me a guidance? Thank you.

Hi, I meant that using 'requests' library (instead of 'urllib.request') you can get access to the API of google translate.
This code works fine:

```
import requests

text = 'Hello world'
url = f"https://translate.google.com/translate_tts?ie=UTF-8&q={text}&tl=en&ttsspeed=1&total=1&idx=0&client=tw-ob&tk=838940.655735"
doc = requests.get(url)
with open("hello_world.mp3", 'wb') as f:
    f.write(doc.content)
```

This doesn't:
```
import urllib.request

text = 'Hello world'
url = f"https://translate.google.com/translate_tts?ie=UTF-8&q={text}&tl=en&ttsspeed=1&total=1&idx=0&client=tw-ob&tk=838940.655735"

urllib.request.urlretrieve(url, "hello_world.mp3")
```

**Comment by redrussianarmy** [comment]
Actually, I get a warning that causes slowness and an error that are logged.
1) `WARNING  |  8433 | gtts.tts | Unable to get language list: 'NoneType' object is not subscriptable`
Warning occurs while instantiating the gTTS class with passing lang as "tr" - Turkish language
2) `ERROR    | 14824 | my_app.tts:_get_audio_seg:58 | Unknown Google TTS issue: Unable to find token seed! Did https://translate.google.com change?`
Error occurs while instantiating the gTTS class

tts object is being created as follow:
`tts = gTTS(text=transcript, lang="tr")`

What could be the reason causing these issues?

**Comment by alexrink96** [comment]
> Actually, I get a warning that causes slowness and an error that are logged.
> 
> 1. `WARNING  |  8433 | gtts.tts | Unable to get language list: 'NoneType' object is not subscriptable`
>    Warning occurs while instantiating the gTTS class with passing lang as "tr" - Turkish language
> 2. `ERROR    | 14824 | my_app.tts:_get_audio_seg:58 | Unknown Google TTS issue: Unable to find token seed! Did https://translate.google.com change?`
>    Error occurs while instantiating the gTTS class
> 
> tts object is being created as follow:
> `tts = gTTS(text=transcript, lang="tr")`
> 
> What could be the reason causing these issues?
> **gTTS==2.1.1 gTTS-token==1.1.3**

I'm not sure what the reason is but I get the same error.

**Comment by redrussianarmy** [comment]
I understand. What about the warning? Do you face with the same warning? @alexrink96

**Comment by pndurette** [comment]
Closing in favour of the discussion in #232
