### ISSUE TITLE
Code duplication in parallel projects

### ISSUE THREAD

**Issue by Boudewijn26** [pndurette/gTTS#23]
Currently [google_speech](https://github.com/desbma/GoogleSpeech) uses the same token generation code as this project. Is it worthwhile to extract the token generation code from this project into a new project and let both projects depend on that? I would be willing to maintain that project.

**Comment by desbma** [comment]
Sounds like a good idea to me, especially if Google starts changing the hash algorithm.

**Comment by pndurette** [comment]
Agreed! That project wouldn't do much on its own, but I'm sure there's more than us two who are using this endpoint. 

--
Pierre Nick Durette

**Comment by Boudewijn26** [comment]
[I think we are live.](https://pypi.python.org/pypi/gTTS-token/1.0.0)

**Comment by pndurette** [comment]
Amazing! Thanks for that. I'll implement it soon.

**Comment by pndurette** [comment]
I was away for a while and totally let this drag on.. I want to do this later today. I see you're already at `1.0.1`! I will let the requirement for `gTTS-token` lonely constrained in `setup.py`.

**Comment by pndurette** [comment]
Done. `gTTS` 1.1.4 is [live](https://pypi.python.org/pypi/gTTS/1.1.4)! Thanks for you work on this @Boudewijn26 . https://github.com/pndurette/gTTS/compare/v1.1.3...v1.1.4
