### ISSUE TITLE
Date Problem

### ISSUE THREAD

**Issue by jhoelzl** [pndurette/gTTS#235]
Hello,

when i use the phrase "5. Nov 2020" with gTTS, it sees the point after the number 5 as a sentence end, therefore the gTTS output is not correct.

However, when i use "5. November 2020" it works.

How can i add this pattern (3 character month names)?

Thanks!

**Comment by amcareem** [comment]
Did you install from pip?

**Comment by pndurette** [comment]
Hi @jhoelzl 

Sorry for responding many years later (😨), going through the outstanding issues. Do you think this is still an issue? I've tried reproducing it, and I'm thinking it could have been the way Google did TTS? This is the code I used:

```python
from gtts import gTTS

text1 = "5. Nov 2020 Bacon ipsum dolor amet filet mignon spare ribs pancetta venison  Sirloin alcatra pork chicken filet mignon  Chuck porchetta alcatra bacon tenderloin  Bacon kielbasa andouille picanha sausage "
text2 = "5. November 2020 Bacon ipsum dolor amet filet mignon spare ribs pancetta venison  Sirloin alcatra pork chicken filet mignon  Chuck porchetta alcatra bacon tenderloin  Bacon kielbasa andouille picanha sausage "

tts = gTTS(text1)
tts = gTTS(text2)

with open("text1.mp3", "wb") as f:
    tts.write_to_fp(f)

with open("text2.mp3", "wb") as f:
    tts.write_to_fp(f)
```

(Added some padding to make it have to split the sentence for processing)

Both `text1.mp3` and `text2.mp3` sound the same, with "November" pronounced properly.

**Comment by pndurette** [comment]
I will close this—let me know if this is still an issue!
