### ISSUE TITLE
Commande-line work, but not the module gTTS

### ISSUE THREAD

**Issue by tlelepvriercussol** [pndurette/gTTS#24]
Hi all.

First, Thanks for your job to find the problem of the new API version.

I'm able to use the `gtts-cli` command line with, for exemple :
`gtts-cli.py "Bonjour" -l 'fr' -o hello.mp3` and play it with the command line `play`, or open it with Itunes.

But when I use the gTTS module, I haven't any problem executing my code, but I can't open the .mp3 (Or other, .flac, ...) with Itunes, And the `play` command return :

`play WARN mp3-util: MAD lost sync
play FAIL formats: can't open input file 'hello2.mp3'`

Here my code :
`from gtts import gTTS
tts = gTTS(text='Hello')
tts.save("hello2.mp3")`

**Comment by pndurette** [comment]
Hi @tlelepvriercussol, I can't reproduce this. It works for me, although I only have QuickTime, VLC and iTunes to try it out on OS X at the moment. Can you give me more info about your environment?

Also, I would like to point out that `gtts-cli` uses that exact code to save the file: https://github.com/pndurette/gTTS/blob/master/bin/gtts-cli.py#L36-L39
