### ISSUE TITLE
gTTS takes 10-15 mins to get audio back.

### ISSUE THREAD

**Issue by CharlieTemplar** [pndurette/gTTS#241]
I have a talking alarm clock, been running for many years.  Recently the morning alarm goes off on time, but the spoken text about date, weather and other news is delayed.  seems to be taking 10 mins for each request, then some all work one after another.
Eventually 30 mins or so later, the text completes and the radio finally starts.
 What is happening?  same happens if I just run gtts-cli hello.
Sometimes I get an error message "Token cannot be found in Google Translate page :/" and the next attempt works straight away.
What's the best way to debug what is happening??
Just pip installed the latest version, but same issue...

**Comment by pndurette** [comment]
@CharlieTemplar Yes, there's discussion in #232. The whole backend is changing, on Google's side. The gent behind `gTTS-token` is also taking a look (https://github.com/pndurette/gTTS/issues/232#issuecomment-724881349), but this could be a big endeavour.
