### ISSUE TITLE
Unable to get language list: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by redrussianarmy** [pndurette/gTTS#242]
Sometimes, I get a warning that causes slowness visibly.

```
`WARNING  |  8433 | gtts.tts | Unable to get language list: 'NoneType' object is not subscriptable`
```
Warning occurs while instantiating the gTTS class with passing lang as "tr" - Turkish language

tts object is being created as follow:
`tts = gTTS(text=transcript, lang="tr")`

What could be the reason causing this issue?
**gTTS==2.1.2
gTTS-token==1.1.4**

_Originally posted by @redrussianarmy in https://github.com/pndurette/gTTS/issues/226#issuecomment-719481955_

**Comment by pndurette** [comment]
Hi @redrussianarmy!

The retrieval of languages has become less reliable. Working on it, to remove the network component. In the meantime, you can pass `--nocheck` to `gtts-cli` or `lang_check=False` to `gTTS()` to skip language checking!
