### ISSUE TITLE
gTTS slow on generating file

### ISSUE THREAD

**Issue by ElCresh** [pndurette/gTTS#243]
Hi,
I've used this library for almost 2 years. I runt a python script on a RPi3 and now when It start generating mp3 file from TTS conversion it locks for aroung 1 minute or more and no output file is generated. This behaviour seems to be randomic. Is there any issue between gTTS and Google Translation system?

**Comment by pndurette** [comment]
Hi @ElCresh, yeah, known issue, we're fixing it! See #232, and also this https://github.com/pndurette/gTTS/issues/233#issuecomment-725781717 which should help in the meantime for your issue!
