### ISSUE TITLE
tts.get_urls() invalid url

### ISSUE THREAD

**Issue by dkdps** [pndurette/gTTS#257]
Using a slightly modified version of the example code in the documentation (https://gtts.readthedocs.io/):

> from gtts import gTTS
> tts = gTTS("hello", lang='en')
> print(tts.get_urls())
> 

The printed URL does not lead to the desired 'hello' sound but only gives me:
'['https://translate.google.com/_/TranslateWebserverUi/data/batchexecute']'

I am on python 3.8.8rc1. Not certain if this is an error or my incorrect use of the library. Any help is appreciated :)

**Comment by pndurette** [comment]
@dkdps Hi! And apologies for this, this is an outdated method that should (and will be) removed. Starting with `2.2.0`, the underlying mechanism to get speech has completely changed and doesn't use HTTP GET anymore. Like you got here it uses only one URL (but the underlying API now uses POST requests).

**Comment by dkdps** [comment]
Ah ok. I found another way to do what I was trying to and it works great otherwise! Cheers for the response!

**Comment by ochen1** [comment]
Is there a temporary workaround for now?

**Comment by ochen1** [comment]
Found a workaround:

```py
def tts_url(text):
    return '?'.join([
        "https://translate.google.com/translate_tts",
        urlencode({
            "ie": "UTF-8",
            "q": quote_plus(text).replace('%20', '+'),
            "tl": "en",
            "ttsspeed": "1",
            "total": "1",
            "idx": "0",
            "client": "tw-ob",
            "textlen": str(len(text))
        })
    ])
```

I don't know what `tk=316070.156329` means but I'm too lazy to reverse engineer the API again and it looks like the endpoint works without it :)

Just make sure to import the required functions from urllib.parse:
```py
from urllib.parse import urlparse, urlencode, quote_plus
```

**Comment by pndurette** [comment]
Hello! gTTS `v2.2.2` is out with fixes for this!
