### ISSUE TITLE
Random warning of Unverified HTTPS request is being made.  

### ISSUE THREAD

**Issue by JDJGInc** [pndurette/gTTS#258]
I would like if I didn't get:
/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
  from using:
   mp3_fp = BytesIO()
    tts=gtts.gTTS(text=args,lang='en')
    tts.write_to_fp(mp3_fp)
    mp3_fp.seek(0)
    file = discord.File(mp3_fp,"tts.mp3")
    await ctx.send(file=file)
    (and if you could, could you make an async version?

**Comment by pndurette** [comment]
gTTS [hides this warning explicitly](https://github.com/pndurette/gTTS/blob/9fd46872523df97a1ccfc58bb8ebc3da93495400/gtts/tts.py#L252), you might have somewhere else in your code where warning filtering is getting reset?
