### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by fidelhuang1** [pndurette/gTTS#259]
I get this eeror:
Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://translate.google.com/_/TranslateWebserverUi/data/batchexecute&q=EgRuTxJDGLyH1v8FIhkA8aeDS1CR5WY9Ha8EtLFH-yKhOBoFDvbuMgFy

can you check it ?

**Comment by Gnome-py** [comment]
I have also been having this error intermittently, very annoying and working on getting a temp proxy up for my application.

**Comment by pndurette** [comment]
Hi, sorry for the late reply!

These errors are out of the control of this library. As the error says, this is Google temporary blocking you from doing too many requests. It does that for any Google URL you hammer too much.

You could implement caching on the strings you speak, or add some throttling perhaps.
