### ISSUE TITLE
gtts.tts.gTTSError: 200 (OK) from TTS API. Probable cause: Unknown

### ISSUE THREAD

**Issue by John-ison** [pndurette/gTTS#265]
I am using version 2.2.1 and it seems like if the language is Chinese, the conversion fails with the following message:
```
Traceback (most recent call last):
  File "C:/Users/John/Documents/github.py", line 4, in <module>
    sound.save("Sound.mp3")
  File "C:\Program Files\Python38\lib\site-packages\gtts\tts.py", line 312, in save
    self.write_to_fp(f)
  File "C:\Program Files\Python38\lib\site-packages\gtts\tts.py", line 294, in write_to_fp
    raise gTTSError(tts=self, response=r)
gtts.tts.gTTSError: 200 (OK) from TTS API. Probable cause: Unknown
```
This is my code:
```
from gtts import gTTS

LANGUAGE = "zh-cn" # "en"

sound = gTTS("你好世界！", lang=LANGUAGE)
sound.save("Sound.mp3")
```
and if you change LANGUAGE back into "en", the program works.

**Comment by glokhoff** [comment]
Having the same issue with english - new zealand (en-nz) as language. ALso en-gb seems to crash, and probably a lot more...

**Comment by depthinvokesu** [comment]
Yes, and if you run something like this in a command line, you will get: "Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'en-us' ". Probably Google have changes their API so that languages from _extra_langs() are not supported anymore

**Comment by pndurette** [comment]
Yeah something def. changed with languages. Let me poke at this.

**Comment by John-ison** [comment]
Thanks.

**Comment by pndurette** [comment]
Hello! gTTS `v2.2.2` is out with fixes for this!
