### ISSUE TITLE
Yes it's possible. You need a module that will play from a file-like/file object. Instead of doing `tts.save()` you can use `tts.write_to_fp()` to write to a file-like object that you can then reuse to play. As a really simple example:

### ISSUE THREAD

**Issue by pankaj251003** [pndurette/gTTS#268]
Yes it's possible. You need a module that will play from a file-like/file object. Instead of doing `tts.save()` you can use `tts.write_to_fp()` to write to a file-like object that you can then reuse to play. As a really simple example:

```
from gtts import gTTS
from tempfile import TemporaryFile
tts = gTTS(text='Hello', lang='en')
f = TemporaryFile()
tts.write_to_fp(f)
# Play f
f.close()
```
How to play this
_Originally posted by @pndurette in https://github.com/pndurette/gTTS/issues/26#issuecomment-187515719_

**Comment by pndurette** [comment]
@pankaj251003 See #26 and #192!
