### ISSUE TITLE
SSL Error during Request

### ISSUE THREAD

**Issue by jhoelzl** [pndurette/gTTS#27]
Hello,

i am using Python 2.7.6 and gTTS 1.1.3 in a Python virtualenv. Everytime, when i try this command 

`tts = gTTS(text='Hello', lang='en')`

i get back a `class 'requests.exceptions.SSLError`. I assume it has something to to with version of Python module `requests` or some other security settings. Can you recommend me which version to use to overcome this issue?

Thanks!
Josef

**Comment by jhoelzl** [comment]
I could solve this issue on my own. I installed module `certifi` with version `2015.11.20.1`, however, only version `2015.4.28` works for me.

**Comment by jaswon5791** [comment]
Hi, I also have encountered this problem, and installing certifi==2015.4.28 did not solve the problem for me.

**Comment by jhoelzl** [comment]
Hi @jaswon5791, unfortunately i am not using Python 2.6 therefore i can not test it. Does it work with Python 2.7?
