### ISSUE TITLE
Multiple Voice Support (Male/Female)

### ISSUE THREAD

**Issue by rcbyron** [pndurette/gTTS#28]
Is it possible to support both Google's (english) male and female voices?

**Comment by pndurette** [comment]
Hi @rcbyron, AFAIK there no way to do this? Do you have any information about this I could look at (and integrate)? This API is undocumented so perhaps I'm missing out on a feature!

**Comment by rcbyron** [comment]
So previously I was under the impression that Google Translate supported both male and female voices. Unfortunately I can't find if or where they do anymore.
