### ISSUE TITLE
Random female and male voices

### ISSUE THREAD

**Issue by DaniGarciaLopez** [pndurette/gTTS#282]
Hi

I tried the new version of the library (2.2.2) and when I play a sound it randomly selects a different voice. I tried with spanish language and it uses either male or female voice randomly. Regarding english it is always a female but changing the entonation.

Is there a way to control it? I did not find anything in the documentation. I tested the library a couple of months ago and it was always using the same voice.

**Comment by pndurette** [comment]
Sadly no, there's no way to pick the voice.

But I'm interested in this situation! 

Were they long sentences? Does it change midway? Can you include samples?

**Comment by DaniGarciaLopez** [comment]
I tried this simple script:
```
from gtts import gTTS
from playsound import playsound

phrase="Esto es una prueba de síntesis de voz"
tts=gTTS(text=phrase, lang='es', tld='es')
filename="voice.wav"

tts.save(filename)
playsound(filename)
```
Sometimes it uses the same female voice that was before but others a new male voice which sounds even better. I tried with a long text and it randomly changes the voice after a full stop. If you cannot replicate it in your computer I can record you some examples.

Thanks!

**Comment by DaniGarciaLopez** [comment]
Looks like is already fixed. Now only male voice is used. Thanks!
