### ISSUE TITLE
Change from female to male voice

### ISSUE THREAD

**Issue by thanhvtr** [pndurette/gTTS#290]
The default voice is female. How can I change to male voice?

**Comment by pndurette** [comment]
Unfortunately not. This module is totally dependent on what Google Translate uses for every language. 

You can try [another locale](https://gtts.readthedocs.io/en/latest/module.html#localized-accents) for your language and see if you get a make voice but even that is not guaranteed.

**Comment by SyamCyberonics** [comment]
you can change the pitch

**Comment by cryptonet0** [comment]
> you can change the pitch

How?

**Comment by SafwanGanz** [comment]
> you can change the pitch

How to change?

**Comment by Drakunal** [comment]
Pitch and all cannot be changed yet
