### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by csi-stasik** [pndurette/gTTS#30]
Hi, I get the error: (Python 2.7)
`requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)`

any fix or workaround? Thank you.

**Comment by jhoelzl** [comment]
Please post your installed modules using `pip list`. I had some similar issues and downgraded the `requests` module to version 1.2.0.

**Comment by csi-stasik** [comment]
There are my modules:

argparse (1.2.1)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
certifi (2016.2.28)
Flask (0.10.1)
Flask-OAuthlib (0.9.2)
Flask-SQLAlchemy (2.1)
gTTS (1.1.4)
gTTS-token (1.0.1)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
oauthlib (1.0.3)
pip (1.5.6)
requests (2.9.1)
requests-oauthlib (0.6.1)
setuptools (5.5.1)
singledispatch (3.4.0.3)
six (1.10.0)
SQLAlchemy (1.0.12)
tornado (4.3)
tornroutes (0.5.1, /var/www/seven-service/.venv/src/tornroutes)
Werkzeug (0.11.4)
wsgiref (0.1.2)

I'll try your fix. Thank you

**Comment by jhoelzl** [comment]
Okay, try to reinstall modules using 

```
pip uninstall modulename
pip installmodulename==version
```
for these modules:
```
requests (1.2.0)
certifi (2015.4.28)
```

This setup has worked for me.

**Comment by csi-stasik** [comment]
Excellent work man. Thanks a lot.

**Comment by pndurette** [comment]
Thanks @jhoelzl !

**Comment by jhoelzl** [comment]
I have the same error when running the script with Python 2.7.9 on armv7l with requests version 2.5.1

I tried this (unsafe) code:


```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

but it does not work with this library although other Speech APIs work again with this code.

Any suggestions?
