### ISSUE TITLE
Unable to find token seed

### ISSUE THREAD

**Issue by PrincessMiki** [pndurette/gTTS#308]
## Prerequisites
* [yes] Did you make sure a similar [issue](../) didn't exist?
* [yes] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

I put in:
gtts-cli 'hello' --output hello.mp3

and it returns:

gtts.tts - WARNING - Unable to get language list: 'NoneType' object is not subscriptable
Usage: gtts-cli [OPTIONS] <text>

Error: Unable to find token seed! Did https://translate.google.com change?

---

this code i'm using is from the example page

**Comment by PrincessMiki** [comment]
@pndurette 

Hi, it's not updated to the newest version. I used `$ pip install gTTS`, again and it gives me:

"Requirement already satisfied: gTTS in /usr/lib/python3/dist-packages (2.0.3)"

**Comment by pndurette** [comment]
It's hard for me to tell, but form the paths in those outputs I see it's doing things in two different locations. Mix of virtual env and system Python.

Try a fresh virtual env, using the latest version of what you use to make virtual envs, without site packages (which is the default now). 

Considering you were having an almost 4 year old version of gTTS, you're probably running a lot of old stuff.

**Comment by PrincessMiki** [comment]
@pndurette 

Fresh install of ubuntu. Maybe apt update/upgrade will fix it? Otherwise, i will try to figure out what virtual envs is, i'm a newb lol

**Comment by pndurette** [comment]
Nice, glad you got it working!
