### ISSUE TITLE
Different voices

### ISSUE THREAD

**Issue by Jo-Dan** [pndurette/gTTS#31]
Not as issue as such but is there any way to use the additional voices that google recently added.
i.e. Male and female voices.
Excellent module by the way, keep up the good work.

**Comment by pndurette** [comment]
> that google recently added
Interesting. I'll have to look into it. Since this is a technically a non-documented API, I'll have to look that up. And thanks!

**Comment by hclivess** [comment]
I tried looking up some information, but haven't found anything. Nevertheless I would also prefer to have more voices to choose from.

**Comment by Mikerhinos** [comment]
I'm interrested in alternative voices too :)
I don't know if it's possible to play with some parameters like to give it a robotic voice, but it would be quite fun, so we can really personnalize our outputs (because even if the actual female voice tone is quite natural, the way that she speaks is pretty robotic).

**Comment by DarthToker** [comment]
http://9to5google.com/2016/02/12/google-tts-voice-sets/

**Comment by andreaskoelsch** [comment]
+1

**Comment by ericpulvino** [comment]
+1

**Comment by RyannDaGreat** [comment]
I found a fix for it. I rewrote the class but I don't know how to use github so here it is: 

class gTTS:# 
    """ gTTS (Google Text to Speech): an interface to Google's Text to Speech API """

    GOOGLE_TTS_URL='https://translate.google.com/translate_tts'
    MAX_CHARS=100  # Max characters the Google TTS API takes at a time
    LANGUAGES={
        'af':'Afrikaans',
        'sq':'Albanian',
        'ar':'Arabic',
        'hy':'Armenian',
        'bn':'Bengali',
        'ca':'Catalan',
        'zh':'Chinese',
        'zh-cn':'Chinese (Mandarin/China)',
        'zh-tw':'Chinese (Mandarin/Taiwan)',
        'zh-yue':'Chinese (Cantonese)',
        'hr':'Croatian',
        'cs':'Czech',
        'da':'Danish',
        'nl':'Dutch',
        'en':'English',
        'en-au':'English (Australia)',
        'en-uk':'English (United Kingdom)',
        'en-us':'English (United States)',
        'eo':'Esperanto',
        'fi':'Finnish',
        'fr':'French',
        'de':'German',
        'el':'Greek',
        'hi':'Hindi',
        'hu':'Hungarian',
        'is':'Icelandic',
        'id':'Indonesian',
        'it':'Italian',
        'ja':'Japanese',
        'ko':'Korean',
        'la':'Latin',
        'lv':'Latvian',
        'mk':'Macedonian',
        'no':'Norwegian',
        'pl':'Polish',
        'pt':'Portuguese',
        'pt-br':'Portuguese (Brazil)',
        'ro':'Romanian',
        'ru':'Russian',
        'sr':'Serbian',
        'sk':'Slovak',
        'es':'Spanish',
        'es-es':'Spanish (Spain)',
        'es-us':'Spanish (United States)',
        'sw':'Swahili',
        'sv':'Swedish',
        'ta':'Tamil',
        'th':'Thai',
        'tr':'Turkish',
        'vi':'Vietnamese',
        'cy':'Welsh'
    }

    def __init__(self,text,lang='en',debug=False):
        self.debug=debug
        if lang.lower() not in self.LANGUAGES:
            raise Exception('Language not supported: %s' % lang)
        else:
            self.lang=lang.lower()

        if not text:
            raise Exception('No text to speak')
        else:
            self.text=text

        # Split text in parts
        if len(text) <= self.MAX_CHARS:
            text_parts=[text]
        else:
            text_parts=self._tokenize(text,self.MAX_CHARS)

            # Clean
        def strip(x):
            return x.replace('\n','').strip()
        text_parts=[strip(x) for x in text_parts]
        text_parts=[x for x in text_parts if len(x) > 0]
        self.text_parts=text_parts

        # Google Translate token
        self.token=Token()

    def save(self,savefile):
        """ Do the Web request and save to `savefile` """
        with open(savefile,'wb') as f:
            self.write_to_fp(f)
            f.close()

    def write_to_fp(self,fp):
        """ Do the Web request and save to a file-like object """
        LANGUAGES={
            'af':'Afrikaans',
            'sq':'Albanian',
            'ar':'Arabic',
            'hy':'Armenian',
            'bn':'Bengali',
            'ca':'Catalan',
            'zh':'Chinese',
            'zh-cn':'Chinese (Mandarin/China)',
            'zh-tw':'Chinese (Mandarin/Taiwan)',
            'zh-yue':'Chinese (Cantonese)',
            'hr':'Croatian',
            'cs':'Czech',
            'da':'Danish',
            'nl':'Dutch',
            'en':'English',
            'en-au':'English (Australia)',
            'en-uk':'English (United Kingdom)',
            'en-us':'English (United States)',
            'eo':'Esperanto',
            'fi':'Finnish',
            'fr':'French',
            'de':'German',
            'el':'Greek',
            'hi':'Hindi',
            'hu':'Hungarian',
            'is':'Icelandic',
            'id':'Indonesian',
            'it':'Italian',
            'ja':'Japanese',
            'ko':'Korean',
            'la':'Latin',
            'lv':'Latvian',
            'mk':'Macedonian',
            'no':'Norwegian',
            'pl':'Polish',
            'pt':'Portuguese',
            'pt-br':'Portuguese (Brazil)',
            'ro':'Romanian',
            'ru':'Russian',
            'sr':'Serbian',
            'sk':'Slovak',
            'es':'Spanish',
            'es-es':'Spanish (Spain)',
            'es-us':'Spanish (United States)',
            'sw':'Swahili',
            'sv':'Swedish',
            'ta':'Tamil',
            'th':'Thai',
            'tr':'Turkish',
            'vi':'Vietnamese',
            'cy':'Welsh'
        }

        for idx,part in enumerate(self.text_parts):
            payload={'ie':'UTF-8',
                     'q':part,
                     'tl':LANGUAGES[self.lang],
                     'total':len(self.text_parts),
                     'idx':idx,
                     'client':'tw-ob',
                     'textlen':len(part),
                     'tk':self.token.calculate_token(part)}
            headers={
                "Referer":"http://translate.google.com/",
                "User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
            }
            if self.debug: print(payload)
            try:
                r=requests.get(self.GOOGLE_TTS_URL,params=payload,headers=headers)
                if self.debug:
                    print("Headers: {}".format(r.request.headers))
                    print("Response: {}, Redirects: {}".format(r.status_code,r.history))
                r.raise_for_status()
                for chunk in r.iter_content(chunk_size=1024):
                    fp.write(chunk)
            except Exception as e:
                raise

    def _tokenize(self,text,max_size):
        """ Tokenizer on basic roman punctuation """

        punc="¡!()[]¿?.,;:—«»\n"
        punc_list=[re.escape(c) for c in punc]
        pattern='|'.join(punc_list)
        parts=re.split(pattern,text)

        min_parts=[]
        for p in parts:
            min_parts+=self._minimize(p," ",max_size)
        return min_parts

    def _minimize(self,thestring,delim,max_size):
        """ Recursive function that splits `thestring` in chunks
        of maximum `max_size` chars delimited by `delim`. Returns list. """

        if len(thestring) > max_size:
            idx=thestring.rfind(delim,0,max_size)
            return [thestring[:idx]] + self._minimize(thestring[idx:],delim,max_size)
        else:
            return [thestring]

**Comment by OliPicard** [comment]
Hey @RyannDaGreat Create a [pull request](https://yangsu.github.io/pull-request-tutorial/) and apend the code with your patch. Then someone can either accept or decline the new code. Hope this helps :-)

**Comment by pndurette** [comment]
@RyannDaGreat 

Hey, thanks for this!
As mentioned above, it is easier to see what changed when a pull request is submitted.
However I did attempt to find the differences (you removed spaces everywhere) and from what I understand, this is it (using the class `LANGUAGES` dict instead of copying it to local scope like you did):

```diff
payload = { 'ie' : 'UTF-8',
            'q' : part,
-            'tl' : self.lang,
+            'tl' : self.LANGUAGES[self.lang],
            'total' : len(self.text_parts),
            'idx' : idx,
            'client' : 'tw-ob',
            'textlen' : len(part),
            'tk' : self.token.calculate_token(part)}
```

Did I get that right?
This does not work, it sets the request payload `tl` parameter to the name string of the language instead of the language code; which Google rejects. What is it you were trying to do?

**Comment by pndurette** [comment]
I still don't think there's a way to change voices using this API. Google operates multiple TTS APIs, some of which offer voices (as mentioned above in this thread). This one is simple and only used by the Google Translate page, as far as I know.

**Comment by nlurker** [comment]
I noticed that the voice changed recently, and sounds more robotic now.  Any idea what changed, or if we might have a choice now?

**Comment by RyannDaGreat** [comment]
Sorry I just saw these lol...I know I'm a bit late but in my package 'rp' there's a function called 'text_to_speech_via_google'

You can find this package with "pip install rp"

I might add a pull request later if you are still interested, but this works:

def text_to_speech_via_google(text: str,voice='en',*,play_sound: bool = True,run_as_thread: bool = True):
    # This only works when online, and has a larger latency than the native OSX text-to-speech function
    # Favorite voices: da
    # region gTTS: My own version of https://github.com/pndurette/gTTS (I modified it so that it can actually play voices from other languages, which it couldn't do before. I put that functionality in a comment because I don't know how to use Github yet (Feb 2017))
    pip_import('requests')
    import re,requests
    pip_import('gtts_token')
    from gtts_token.gtts_token import Token
    mp3_file_path=temporary_file_path('mp3')
    class gTTS:
        """ gTTS (Google Text to Speech): an interface to Google'_s Text to Speech API """

        GOOGLE_TTS_URL='https://translate.google.com/translate_tts'
        MAX_CHARS=100  # Max characters the Google TTS API takes at a time
        LANGUAGES={
            'af':'Afrikaans',
            'sq':'Albanian',
            'ar':'Arabic',
            'hy':'Armenian',
            'bn':'Bengali',
            'ca':'Catalan',
            'zh':'Chinese',
            'zh-cn':'Chinese (Mandarin/China)',
            'zh-tw':'Chinese (Mandarin/Taiwan)',
            'zh-yue':'Chinese (Cantonese)',
            'hr':'Croatian',
            'cs':'Czech',
            'da':'Danish',
            'nl':'Dutch',
            'en':'English',
            'en-au':'English (Australia)',
            'en-uk':'English (United Kingdom)',
            'en-us':'English (United States)',
            'eo':'Esperanto',
            'fi':'Finnish',
            'fr':'French',
            'de':'German',
            'el':'Greek',
            'hi':'Hindi',
            'hu':'Hungarian',
            'is':'Icelandic',
            'id':'Indonesian',
            'it':'Italian',
            'ja':'Japanese',
            'ko':'Korean',
            'la':'Latin',
            'lv':'Latvian',
            'mk':'Macedonian',
            'no':'Norwegian',
            'pl':'Polish',
            'pt':'Portuguese',
            'pt-br':'Portuguese (Brazil)',
            'ro':'Romanian',
            'ru':'Russian',
            'sr':'Serbian',
            'sk':'Slovak',
            'es':'Spanish',
            'es-es':'Spanish (Spain)',
            'es-us':'Spanish (United States)',
            'sw':'Swahili',
            'sv':'Swedish',
            'ta':'Tamil',
            'th':'Thai',
            'tr':'Turkish',
            'vi':'Vietnamese',
            'cy':'Welsh'
        }

        def __init__(self,text,lang='en',debug=False):
            self.debug=debug
            if lang.lower() not in self.LANGUAGES:
                raise Exception('Language not supported: %s' % lang)
            else:
                self.lang=lang.lower()

            if not text:
                raise Exception('No text to speak')
            else:
                self.text=text

            # Split text in parts
            if len(text) <= self.MAX_CHARS:
                text_parts=[text]
            else:
                text_parts=self._tokenize(text,self.MAX_CHARS)

                # Clean
            def strip(x):
                return x.replace('\n','').strip()
            text_parts=[strip(x) for x in text_parts]
            text_parts=[x for x in text_parts if len(x) > 0]
            self.text_parts=text_parts

            # Google Translate token
            self.token=Token()

        def save(self,savefile):
            """ Do the Web request and save to `savefile` """
            with open(savefile,'wb') as f:
                self.write_to_fp(f)
                f.close()

        def write_to_fp(self,fp):
            LANGUAGES={'af':'Afrikaans','sq':'Albanian','ar':'Arabic','hy':'Armenian','bn':'Bengali','ca':'Catalan','zh':'Chinese','zh-cn':'Chinese (Mandarin/China)','zh-tw':'Chinese (Mandarin/Taiwan)','zh-yue':'Chinese (Cantonese)','hr':'Croatian','cs':'Czech','da':'Danish','nl':'Dutch','en':'English','en-au':'English (Australia)','en-uk':'English (United Kingdom)','en-us':'English (United States)','eo':'Esperanto','fi':'Finnish','fr':'French','de':'German','el':'Greek','hi':'Hindi','hu':'Hungarian','is':'Icelandic','id':'Indonesian','it':'Italian','ja':'Japanese','ko':'Korean','la':'Latin','lv':'Latvian','mk':'Macedonian','no':'Norwegian','pl':'Polish','pt':'Portuguese','pt-br':'Portuguese (Brazil)','ro':'Romanian','ru':'Russian','sr':'Serbian','sk':'Slovak','es':'Spanish','es-es':'Spanish (Spain)','es-us':'Spanish (United States)','sw':'Swahili','sv':'Swedish','ta':'Tamil','th':'Thai','tr':'Turkish','vi':'Vietnamese','cy':'Welsh'}
            """ Do the Web request and save to a file-like object """
            for idx,part in enumerate(self.text_parts):
                payload={'ie':'UTF-8',
                         'q':part,
                         'tl':self.lang,
                         'total':len(self.text_parts),
                         'idx':idx,
                         'client':'tw-ob',
                         'textlen':len(part),
                         'tk':self.token.calculate_token(part)}
                headers={
                    "Referer":"http://translate.google.com/",
                    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
                }
                if self.debug: print(payload)
                try:
                    r=requests.get(self.GOOGLE_TTS_URL,params=payload,headers=headers)
                    if self.debug:
                        print("Headers: {}".format(r.request.headers))
                        print("Reponse: {}, Redirects: {}".format(r.status_code,r.history))
                    r.raise_for_status()
                    for chunk in r.iter_content(chunk_size=1024):
                        fp.write(chunk)
                except Exception as e:
                    raise

        def _tokenize(self,text,max_size):
            """ Tokenizer on basic roman punctuation """

            punc="¡!()[]¿?.,;:—«»\n"
            punc_list=[re.escape(c) for c in punc]
            pattern='|'.join(punc_list)
            parts=re.split(pattern,text)

            min_parts=[]
            for p in parts:
                min_parts+=self._minimize(p," ",max_size)
            return min_parts

        def _minimize(self,thestring,delim,max_size):
            """ Recursive function that splits `thestring` in chunks
            of maximum `max_size` chars delimited by `delim`. Returns list. """

            if len(thestring) > max_size:
                idx=thestring.rfind(delim,0,max_size)
                return [thestring[:idx]] + self._minimize(thestring[idx:],delim,max_size)
            else:
                return [thestring]
                # endregion
    # endregion
    if run_as_thread:
        return run_as_new_thread(text_to_speech_via_google(text=text,voice=voice,mp3_file_path=mp3_file_path,play_sound=play_sound,run_as_thread=False))
    # Note that this method has to save a sound file in order for it to work. I put a default sound_file_path so that it will overwrite itself each time, so that I can avoid putting a ,delete_sound_file_afterwards:bool=True parameter in there (in case you do infact want to save a file)
    # NOTE: sound_file_path is only compatible with .mp3 files, so don't try putting a wav extension on it (it will break it)!
    lang=voice
    assert lang in text_to_speech_voices_for_google,'r.text_to_speech_via_google: The language you input, "' + lang + '", is not a valid option! Please choose one of the following values for lang instead: ' + ', '.join(text_to_speech_voices_for_google)  # These are the available languages we can choose from.

    if not (text,lang) in _text_to_speech_via_google_sound_cache:
        gTTS(text=text,lang=lang).save(mp3_file_path)  # gTTS is a class, and .save is a function of an instance of that class.
        _text_to_speech_via_google_sound_cache[text,lang]=load_sound_file(mp3_file_path,samplerate=True)
        
    samples,samplerate=_text_to_speech_via_google_sound_cache[text,lang]
    if play_sound:
        play_sound_from_samples(samples,samplerate)
    if file_exists(mp3_file_path):
        delete_file(mp3_file_path)

**Comment by pndurette** [comment]
> I noticed that the voice changed recently, and sounds more robotic now.  Any idea what changed, or if we might have a choice now?

Yeah, Google changed again. The choice of 'accent' seems to be strictly derived from the location of the request. ie 'en' called from the Uk would have a British accent. They seem to have removed the choice. Working on an update (#267).

**Comment by pndurette** [comment]
@RyannDaGreat 

Hey there! Pardon my ignorance, but I don't understand how you get support for additional voices in this code? You're just using language codes as far as I can tell.

Also, this is simply a really old version of this library and, this code probably doesn't work anymore. gTTS-token isn't used anymore. 2.2.0 of gTTS has to implement a whole new upstream API.

**Comment by RyannDaGreat** [comment]
Ah - yes you're right, it doesn't work any more...weird, I actually used this code less than a year ago...it used to give multiple voices. I guess I'll have to update my library lol. I see you've added a --lang option to your code though, so I'll just use that :) Thank you
