### ISSUE TITLE
com tld and en lang is like co.uk voice

### ISSUE THREAD

**Issue by ooliver1** [pndurette/gTTS#313]
## Prerequisites
* [yes] Did you make sure a similar [issue](../) didn't exist?
* [yes] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)
```bash
ooliver@tooty:~/projects/tooty$ python3.8 -m pip install -U gTTS
Requirement already up-to-date: gTTS in /home/ooliver/.local/lib/python3.8/site-packages (2.2.3)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from gTTS) (2.22.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from gTTS) (1.14.0)
Requirement already satisfied, skipping upgrade: click in /home/ooliver/.local/lib/python3.8/site-packages (from gTTS) (8.0.1)
ooliver@tooty:~/projects/tooty$ 
```

## Current Behaviour (steps to reproduce)

british accent not american

```py
speech = gTTS(text=text, slow=False, lang="en", tld="com")
```

## Expected Behaviour

american accent

## Context

I would like to use the american accent too

## Environment

* gTTS version: 2.2.3
* Operating System version: Ubuntu 20.04.2 LTS

**Comment by tealc-indeed** [comment]
same on arch linux, gTTS version: 2.2.3

**Comment by ooliver1** [comment]
us works yep, maybe edit docs for that

**Comment by ooliver1** [comment]
it as also a very random change

**Comment by PanderMusubi** [comment]
tld isn't working at the moment, see https://github.com/pndurette/gTTS/issues/363 and https://github.com/pndurette/gTTS/issues/382

**Comment by pndurette** [comment]
@PanderMusubi This is unrelated—

The situation here is that when reaching `google.com` it will redirect you to the one relative to your geographical location. So the English will sound closer to the English in your locale (according to Google). 

It's hard for me to test as I'm in North America, however I think here the solution is that `tld=us` can give US English, notwithstanding where the code is run.

This is more about documenting the behaviour than an issue.
