### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: 

### ISSUE THREAD

**Issue by arsanious** [pndurette/gTTS#32]
This used to work, but started failing all of a sudden. 

```
Traceback (most recent call last):
  File "simple.py", line 29, in <module>
    tts.save(CLIP_NAME)
  File "/usr/lib/python2.7/site-packages/gtts/tts.py", line 94, in save
    self.write_to_fp(f)
  File "/usr/lib/python2.7/site-packages/gtts/tts.py", line 118, in write_to_fp
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://translate.google.com/translate_tts?q=hello&tl=en&client=t&textlen=5&idx=0&total=1&ie=UTF-8&tk=295461.176510
```

**Comment by nihal111** [comment]
Found the same issue. When I ran this today.

**Comment by jakeyjdavis** [comment]
Me too

**Comment by ignalex** [comment]
same

**Comment by emanuelioanmuraru** [comment]
Same, what did Google change now

**Comment by Pandhariix** [comment]
Same here

**Comment by Rogergonzalez21** [comment]
I also have this problem. No fixes to this yet?

**Comment by lewisling** [comment]
Yes, I have the same problem. Tests are working fine 12 hours ago.

**Comment by rhsu0268** [comment]
Same problem here. I love this module very much. Hopefully we will get a resolution soon.

**Comment by jakeyjdavis** [comment]
if anyone needs anything urgent here is an online tts service that uses google translate that i think still works, the url is http://soundoftext.com, to get a sound use this http://soundoftext.com/static/sounds/en/hello_my_name_is.mp3

**Comment by pndurette** [comment]
Seems Google changed something.. Sigh. Will have to look at it. Hopefully
we can recover from this one.

On Wed, May 11, 2016 at 8:47 PM, Azita MIND Service <
notifications@github.com> wrote:

> Yes, I have the same problem. Tests are working fine 12 hours ago.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pndurette/gTTS/issues/32#issuecomment-218631053>
>



-- 
Pierre Nicolas Durette
(647) 871-3274 | pndurette@gmail.com
http://www.pierre-nick.com

**Comment by arsanious** [comment]
so this works
`http://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&textlen=32&client=tw-ob&q=hello&tl=En-gb`

this (from the gTTS api) doesn't
`https://translate.google.com/translate_tts?q=hello&tl=en&client=t&textlen=5&idx=0&total=1&ie=UTF-8&tk=295461.176510`

**Comment by ignalex** [comment]
thanks arsanious for the links.
if replacing

*client=t*

 in the gTTS link with

*client=tw-ob*

it works (for me).
btw strange thing = the voice is slightly different .

**Comment by ignalex** [comment]
this fixed it:
in gtts.py
line 105
change to
'client' : 'tw-ob',

and sexy google voice is back.
although don't know if the solution would work for everybody and / or
permanent.
looks google guys monitor IPs from which requests been sent (maybe
considering client?) and block (for a client?)

**Comment by pndurette** [comment]
I had to do that in the past, I remember. Thanks so much for finding this!
Will made and test the change shortly.

On Thu, May 12, 2016 at 5:05 PM, Alex <notifications@github.com> wrote:

> this fixed it:
> in gtts.py
> line 105
> change to
> 'client' : 'tw-ob',
>
> and sexy google voice is back.
> although don't know if the solution would work for everybody and / or
> permanent.
> looks google guys monitor IPs from which requests been sent (maybe
> considering client?) and block (for a client?)
>
>
> On 13 May 2016 at 06:17, Alexander Ignatov <ignalex@gmail.com> wrote:
>
> > thanks arsanious for the links.
> > if replacing
> >
> > *client=t*
> >
> > in the gTTS link with
> >
> > *client=tw-ob*
> >
> > it works (for me).
> > btw strange thing = the voice is slightly different .
> >
> > On 13 May 2016 at 02:48, arsanious <notifications@github.com> wrote:
> >
> >> so this works
> >>
> >>
> http://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&textlen=32&client=tw-ob&q=hello&tl=En-gb
> >>
> >> this (from the gTTS api) doesn't
> >>
> >>
> https://translate.google.com/translate_tts?q=hello&tl=en&client=t&textlen=5&idx=0&total=1&ie=UTF-8&tk=295461.176510
> >>
> >> —
> >> You are receiving this because you commented.
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/pndurette/gTTS/issues/32#issuecomment-218817052>
> >>
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/pndurette/gTTS/issues/32#issuecomment-218885767>
>



-- 
Pierre Nicolas Durette
(647) 871-3274 | pndurette@gmail.com
http://www.pierre-nick.com

**Comment by nihal111** [comment]
@pndurette Why did you revert to `client=t` from `client=tw-ob'? Does google keep this link changing?

**Comment by pndurette** [comment]
As I remember it that argument had to be equal to something else before. 

--
Pierre Nick Durette

**Comment by BrunoKruz** [comment]
I made the change in the client parameter and now are working again.

**Comment by pndurette** [comment]
Thanks @arsanious, @ignalex and everyone for reporting and especially finding the solution so quickly. Releasing a new version with the fix. Will report once it's out.

**Comment by pndurette** [comment]
`gtts 1.1.5` was released to [PyPi](https://pypi.python.org/pypi/gTTS/1.1.5)! [Changelog](https://github.com/pndurette/gTTS/compare/v1.1.4...v1.1.5) 😄
