### ISSUE TITLE
A Way To Get A Dictionary Of Accents

### ISSUE THREAD

**Issue by Pysics** [pndurette/gTTS#331]
## Prerequisites
* [x] Did you make sure a similar [issue](../) didn't exist?
* [x] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

## Proposed Behaviour
There should be a way to get a dictionary of available accents, just like there is a way to get a dictionary of languages:
```py
# Getting languages
gtts.lang.tts_langs()

# A similar function for accents could be like this
gtts.lang.tts_lang_accents()
```

## Context
It is currently not possible to retrieve any data regarding accents.

**Comment by Pysics** [comment]
@pndurette Is this possible?

**Comment by pndurette** [comment]
@Pysics Sorry for the delay on this—
So this 'dictionary of accent' is only there for reference for now (it was created by a contributor who had created one for their own uses), and isn't used by the application at all. It might be in the future, but this is something that's not programmatic at the moment, nor is it maintained.
