### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JeroenConnectivity** [pndurette/gTTS#35]
Is it true that the service is down?

**Comment by pndurette** [comment]
@JeroenConnectivity Have you upgraded to the latest version? There was a breaking API change that was fixed in `1.1.5`. If you have, can you give me more details about what you're experiencing?

**Comment by JeroenConnectivity** [comment]
Seems like the npm package I'm using is not yet updated. So outside the scope of this repository. Thanks for support!

FYI:  https://www.npmjs.com/package/gtts

**Comment by pndurette** [comment]
Ha! I had no idea this existed. Yeah, contact the author to fix that package. This is the fix they should apply. https://github.com/pndurette/gTTS/commit/e45b70dd3af7f54d90c4c362f668ebce30352c98
