### ISSUE TITLE
Error: Unable to find token seed! Did https://translate.google.com change?

### ISSUE THREAD

**Issue by manuelcaeiro** [pndurette/gTTS#354]
This is what I get when trying to use gtts-cli.
(Tried on 2 machines, one Debian and one Ubuntu.)

****@****:~$ gtts-cli 'this is a test' --output test.mp3
gtts.tts - WARNING - Unable to get language list: 'NoneType' object is not subscriptable
Usage: gtts-cli [OPTIONS] <text>
Error: Unable to find token seed! Did https://translate.google.com change?

Is this a case of "Breaking upstream changes can occur without notice."

**Comment by pndurette** [comment]
@manuelcaeiro Hi there! From the looks of it, you're using an old version. Try updating, should work!
