### ISSUE TITLE
requests.exceptions.SSLError > add option to call requests with param verify=False

### ISSUE THREAD

**Issue by ignalex** [pndurette/gTTS#36]
hi guys, 
it is not s big issue, but if you are behind a corp firewall (I am) when trying to call tts.save, there is error with regards to SSL: 

> > > tts.save("hello.mp3")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Anaconda\lib\site-packages\gtts\tts.py", line 94, in save
> > >     self.write_to_fp(f)
> > >   File "C:\Anaconda\lib\site-packages\gtts\tts.py", line 114, in write_to_fp
> > >     r = requests.get(self.GOOGLE_TTS_URL, params=payload, headers=headers)
> > >   File "C:\Anaconda\lib\site-packages\requests\api.py", line 55, in get
> > >     return request('get', url, *_kwargs)
> > >   File "C:\Anaconda\lib\site-packages\requests\api.py", line 44, in request
> > >     return session.request(method=method, url=url, *_kwargs)
> > >   File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 456, in request
> > >     resp = self.send(prep, *_send_kwargs)
> > >   File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 559, in send
> > >     r = adapter.send(request, *_kwargs)
> > >   File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 382, in send
> > >     raise SSLError(e, request=request)
> > > requests.exceptions.SSLError

it is fixed by modifying line 114 from 
r = requests.get(self.GOOGLE_TTS_URL, params=payload, headers=headers)
to 
r = requests.get(self.GOOGLE_TTS_URL, params=payload, headers=headers,verify=False)

could be helpful to maybe having it as an option configurable when building tts object. 

Cheers 
Alex

**Comment by foges** [comment]
Similar issue here. I get `requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)`

**Comment by jhoelzl** [comment]
Me too!

I can suppress the error when i add the option `verify=False` to the request command in the gtts_token package on line [58](https://github.com/Boudewijn26/gTTS-token/blob/master/gtts_token/gtts_token.py#L58).

However, i am also searching for a better solution ...

**Comment by wallygit** [comment]
Hello,
I installed gtts using "pip install gTTS" and I get the ssl error when trying the commandline utility:
gtts-cli.py "Hello" -l 'en' -o hello.mp3
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

I tried to reinstall requests and certifi but no change.
How should I try the above approach ?
> r = requests.get(self.GOOGLE_TTS_URL, params=payload, headers=headers)
> change to
> r = requests.get(self.GOOGLE_TTS_URL, params=payload, headers=headers,verify=False)

After changing .../gTTS-master/gtts/tts.py line 114 I assume I have to rbuild the utility (?)
Simply using "pip install gTTS" again, seems to download a fresh source and my changes are ignored.
I'm not experienced with Python stuff at all, I just need to use the tool to make some text available for vison impaired. Any help highly welcome, thx.

**Comment by ruapotato** [comment]
Work around:

in 
`/usr/lib/python3.4/site-packages/requests/sessions.py`

change line 572 from:
```       
        # Send the request
        r = adapter.send(request, **kwargs)
```
to read
```
        # Send the request
        kwargs['verify'] = False
        r = adapter.send(request, **kwargs)
```

**Comment by wallygit** [comment]
works now, thank you very much !

**Comment by pndurette** [comment]
Hi! [gTTS 1.20](https://pypi.python.org/pypi/gTTS/1.2.0) was released, fixing this. SSL verify is now always false, since we can live w/o it in our case.

**Comment by souzaavi** [comment]
After making changes use these lines of code in the file where u are using tts.save() to avoid warnings.

import urllib3

urllib3.disable_warnings()
