### ISSUE TITLE
Timestamps of the spoken words

### ISSUE THREAD

**Issue by olgabaranov** [pndurette/gTTS#398]
Is it possible to retrieve the timing of the spoken words from the gtts itself? (Like the ones that will be used in srt subtitle files, though I don't care about the exact format) 
I know that there might be hacky ways of speech-to-text'ing it back or splitting text into separate word, but I would prefer not to go this route.

**Comment by pndurette** [comment]
Sorry for the delay—
Yeah, hmm that would be pretty difficult for what this library does (which is request a byte stream and saving it to a file), so there's nothing really that it could directly do for this, since it's not really aware of the resulting data.
