### ISSUE TITLE
add support to control the speed of TTS

### ISSUE THREAD

**Issue by lanewu** [pndurette/gTTS#40]
can you add options include: Very slow; Slow; Normal; Fast; Faster; Very fast; Rapid; Very rapid; Fastest, etc.?

**Comment by berk-can** [comment]
@lanewu 
you can use speed option of your media player while playing .mp3 file, like 'mplayer --speed xx test.mp3'
I know it is not what you wanted but it saves the day

**Comment by pndurette** [comment]
Hi, sorry for the crazy delay on this! I'm reviewing past open issues that were more feature requests than bugs.

There *is* a way that someone found out to control speed, as I mentioned in #41. I plan to add this to the next big release.

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released, adding this. Note that there's only 2 speeds available, normal and slow. This is what the Google API provides.
