### ISSUE TITLE
Proxy setting parameters need to be added

### ISSUE THREAD

**Issue by zwssunny** [pndurette/gTTS#402]
## Prerequisites
* [x] Did you make sure a similar [issue](../) didn't exist?
* [x] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

## Proposed Behaviour
Can you increase the proxy setting parameters, because in some cases in China, you can’t connect to the external network
gTTs can be used with the global proxy enabled, but other applications will be affected. So I don't want to, just make this part of the call go through the proxy
## Context
  File "/home/jackson/.local/lib/python3.10/site-packages/gtts/tts.py", line 277, in stream
    raise gTTSError(tts=self)
gtts.tts.gTTSError: Failed to connect. Probable cause: Unknown

**Comment by pndurette** [comment]
Hi @zwssunny!

So this should be better documented, but it's possible to set proxy settings with environment variables via the way `requests` handles it. See [here](https://docs.python-requests.org/en/latest/user/advanced/#proxies), specifically that part:

> When the proxies configuration is not overridden per request as shown above, Requests relies on the proxy configuration defined by standard environment variables http_proxy, https_proxy, no_proxy, and all_proxy. Uppercase variants of these variables are also supported. You can therefore set them to configure Requests (only set the ones relevant to your needs):

```bash
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
$ export ALL_PROXY="socks5://10.10.1.10:3434"

$ python
>>> import requests
>>> requests.get('http://example.org')
```

**Comment by zwssunny** [comment]
Hi@pndurette 
I know how to do it, I modified the program and submitted it, please merge it without affecting the original function
Thanks!

**Comment by zwssunny** [comment]
I found urllib.request.getproxies() return {}
![image](https://user-images.githubusercontent.com/14110660/229092065-c8b842d5-b40c-4db5-80bd-1e30f5db9c5c.png)

**Comment by pndurette** [comment]
Thanks for #403! I've added some comments!
