### ISSUE TITLE
Want support for LT lithuanian lang

### ISSUE THREAD

**Issue by NeLagina** [pndurette/gTTS#430]
Want support for LT lithuanian lang or give me some details to how can i add it ?

**Comment by NeLagina** [comment]
this is not a issue just wanted to give a feature ticket

**Comment by pndurette** [comment]
Hi @NeLagina 

This library doesn't control which languages get added, it simply interfaces with the ones Google Translate has available for speech! Sadly Lithuanian isn't one of them!

This repo has a weekly task that runs to check for any new available languages, and adds them as soon as they'd become available.
