### ISSUE TITLE
Possible to add support for neural wavenet and studio?

### ISSUE THREAD

**Issue by mxav1111** [pndurette/gTTS#439]
## Prerequisites
* [ ] Did you make sure a similar [issue](../) didn't exist? Yes. It exists for simple text but unable to find anything that can take text file as input for neural voices and create an audio file.
* [ ] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)
Yes

## Proposed Behaviour

--all to provide the list of  all additional supported neural/wavenet voices.
-l     to allow these neural/wavenet/studio  language voices

```
code
```

## Context
 Trying to use neural languages.

Old books converted from scanned pdf to text can be translated into realistic voices.

Thanks for your help.

**Comment by pndurette** [comment]
Sorry, but this library even if Google-related, doesn't do neural/wavenet voices, which are an actual Google Cloud product.

I'm not sure if there's any easy-to-use CLI that already allows this, but I'm not planning on making one in the immediate future (maybe one day)
