### ISSUE TITLE
readthedocs out of date

### ISSUE THREAD

**Issue by austin-bowen** [pndurette/gTTS#444]
It looks like the docs haven't updated in the past couple releases:

https://gtts.readthedocs.io/

Perhaps the `.readthedocs.yaml` is missing some keys and that's causing the build to fail. Here is their [template](https://docs.readthedocs.io/en/stable/config-file/v2.html).

Also I recommend updating the old `http://gtts.readthedocs.org/` link in the README to match the new URL (https + .io).

**Comment by pndurette** [comment]
Fixed by #445
