### ISSUE TITLE
SD106 appears to mean South Dakota 106

### ISSUE THREAD

**Issue by dermotgouk** [pndurette/gTTS#470]
## Prerequisites
* [x] Did you make sure a similar [issue](../) didn't exist?
* [x] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

## Current Behaviour (steps to reproduce)

Related the the same issue I posted about " and feet. I am now getting the transcription of SD106 as South Dakota 106, but when I add some quotation marks it fixes itself.
(https://github.com/pndurette/gTTS/issues/447#issue-2068459367)

```
                finished = (Space 4,SD106,Operational,Space 4)
                finishing =str(finished)
                print(finishing)
                var= gTTS(text = finishing,lang = 'en') 
                var.save('eng.mp3')
```

How it looks the way I have fixed it:

```
                finished = (Space 4, ", SD106, ",Operational,Space 4)
                finishing =str(finished)
                print(finishing)
                var= gTTS(text = finishing,lang = 'en') 
                var.save('eng.mp3')
```

## Expected Behaviour

It should say:
> _es di one zero six_

## Context

Work around works but is not too clean

## Environment

gTTS version: 2.5.1
Operating System version: Windows 11

**Comment by pndurette** [comment]
Sorry I'm late to this, but this is indeed the same issue as #447 and is the exact same fix. You're not converting your tuple properly so your string to read is full of extra punctuation, which yeah can have weird results.

See my comment, same thing: https://github.com/pndurette/gTTS/issues/447#issuecomment-1880105901
