### ISSUE TITLE
Problems with char "á"

### ISSUE THREAD

**Issue by lmarmisa** [pndurette/gTTS#48]
Many languages use accented vowels. Spanish is one of them. I am using UTF-8 encoding. Apparently the lower case vowel "a" with acute accent "á" (0xC3 0xA1 (c3a1)) is not recognized in the text by your program. The same accented vowel in upper case "Á" (0xC3 0x81 (c381)) works properly. The other accented lower case vowels ("é", "í", "ó", "ú") works fine too. The behaviour in other languages like Italian or French seems just the same than in Spanish (es-es or es-us). Therefore the problem seems limited to the char "á".

Best regards,

Luis

**Comment by Sithdown** [comment]
It seems the same happens with "ñ", but not "Ñ".

**Comment by augustochaos** [comment]
I solve this problem declaring enconding:

#!/usr/bin/python
# -*- coding: latin-1 -*-

**Comment by pndurette** [comment]
Same issue it seems as #9. I need to investigate encoding better. It seems to work on the site but not in gTTS. Will work on this.

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released, with a lot of changes.

Trying `á` with both Google Translate on the Web and `gTTS` gave me the exact same url, so hopefully this works for all of us. In my own tests (using the class directly or with the cli, it worked as well).  I mostly did my tests with the word `árbol`
