### ISSUE TITLE
Whether to add proxy parameters?

### ISSUE THREAD

**Issue by advancejar** [pndurette/gTTS#489]
I am a user from China , as you know Google service don't work here.

Whether to add proxy parameters?

**Comment by pndurette** [comment]
Yes it's possible to set proxies!
You can't pass them directly, but you can use the `HTTP_PROXY` (or `HTTPS_PROXY`) environment variable, which will get picked up automatically by requests: https://docs.python-requests.org/en/latest/user/advanced/#proxies
