### ISSUE TITLE
gTTS not wanting to import properly

### ISSUE THREAD

**Issue by philipposslicher** [pndurette/gTTS#50]
So I am trying to get gTTS to work
I know that you are supposed to import with `from gtts import gTTS`.
I have a new virtualenv, with gtts, and speechrecognition installed and no matter what I do I can't get gTTS to import
If I try: `from gtts import gTTS`
`ImportError: cannot import name 'gTTS'`
Any ideas?
Using Python `3.5.2`

**Comment by jhoelzl** [comment]
How have you installed the module?

When you have activated your virtual environment, run

`pip install gTTS` without `sudo`, otherwise it will be installed in your main python folder of your operating system.

**Comment by philipposslicher** [comment]
I installed it with `pip install gTTS'. I have checked its installed in the virtualenv, running `import gtts` (I ran this just to test if its installed) shows thats its installed .

**Comment by jhoelzl** [comment]
and in your environment, the module files exist under `lib/python3.5/site-packages/gtts` ?

**Comment by philipposslicher** [comment]
Yep, both gtts, and gtts_token and gTTS_token-1.1.1.dist-info

**Comment by jhoelzl** [comment]
Could you try the command `from gtts import gTTS` using `python -i` in your environment?

**Comment by philipposslicher** [comment]
It gives me this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'gTTS'

**Comment by jhoelzl** [comment]
You could try this instead:

```
import gtts

tts = gtts.gTTS(text='Hello', lang='en')
tts.save("hello.mp3")
```

**Comment by philipposslicher** [comment]
That gives this though:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gtts' has no attribute 'gTTS'
```

**Comment by jhoelzl** [comment]
Maybe this is related to http://stackoverflow.com/questions/16981921/relative-imports-in-python-3.

Maybe try something like this:

```
import gtts

tts = gtts.tts.gTTS(text='Hello', lang='en')
tts.save("hello.mp3")
```
or remove the dots in the import command in `__init__`.py

**Comment by philipposslicher** [comment]
Ok so it I didn't know that the script shouldnt be named after the module. I have fixed it and now it seems to run. Now I'm wondering, is it possible for gTTS to speak the text without needing to write to a file, then playing it back?

**Comment by jhoelzl** [comment]
Currently not, i also requested this feature in #26

**Comment by philipposslicher** [comment]
What would be recommended for playing a file, and also deleting (cause it would be temp)

**Comment by jhoelzl** [comment]
You can do this to play the file and then remove it:

```
from gtts import gTTS
import os

filename = "temp"
tts = gTTS(text='Hello', lang='en')
tts.save(filename + ".mp3")

# Convert MP3 to Wav and Play
os.system('avconv -i ' + filename + '.mp3 -ac 1 -ar 44100 '  + filename + '.wav' )
os.system('aplay ' + filename+'.wav')

os.remove(filename+'.wav')
os.remove(filename+'.mp3')
```

**Comment by Abhishekdiwate** [comment]
@philipposslicher 
I am also having the same problem with gtts module how did you corrected can you pls explain it.
AttributeError: module 'gtts_1' has no attribute 'gTTs'

**Comment by JaiSh12345** [comment]
I wrote `>>import gtts`
I am getting:
`Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    import gtts
  File "C:\Python34\lib\gtts\__init__.py", line 3, in <module>
    from .tts import gTTS, gTTSError
  File "C:\Python34\lib\gtts\tts.py", line 6, in <module>
    from gtts_token import gtts_token
ImportError: No module named 'gtts_token'`
What to do?

**Comment by JaiSh12345** [comment]
Then I tried:
`>>> from gtts import gTTS`
`>>> gTTS('Hello')`
Output? This:
`Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    gTTS('Hello')
  File "C:\Python34\lib\gtts\tts.py", line 140, in __init__
    self.token = gtts_token.Token()
NameError: name 'gtts_token' is not defined`

**Comment by seriadiallo** [comment]
hello rerun this command first 

> pip install gTTS 
it seems that this command crashed ,
then retry

**Comment by redixhumayun** [comment]
Hi, this seems to still be an issue. 

I am using 
-macOS Mojave 10.14.3
-Python 3.7
-gTTs 2.0.3
-gTTs-token 1.1.3

**Comment by Manster2511** [comment]
Traceback (most recent call last):
  File "C:/python/assistant.py", line 1, in <module>
    from gtts import gTTS
ModuleNotFoundError: No module named 'gtts'


Please help with this. It says module not found I checked Its was there, but still got this error...

**Comment by ajayprajapat171** [comment]
Traceback (most recent call last):
File "C:/python/assistant.py", line 1, in
from gtts import gTTS
ModuleNotFoundError: No module named 'gtts'

Please help with this. its same problem coming in my side if you have any solution please help me

**Comment by Manster2511** [comment]
Brother, @ajayprajapat171, when I can't find out what's the error is... I just **unistalled** and reinstalled... **finally error got solved**

**Comment by Devil-Developer** [comment]
> Brother, @ajayprajapat171, when I can't find out what's the error is... I just **unistalled** and reinstalled... **finally error got solved**

Thanks brother.. i tried this way and finally fixed out..

**Comment by AndresVilla123** [comment]
Is true, I unistalled and reinstalled. 
Now it works.
