### ISSUE TITLE
Cannot run from editor and IPython

### ISSUE THREAD

**Issue by tranquockhue** [pndurette/gTTS#51]
I installed gTTS 4 days ago. At first, I used the example and run the script from the editor. It was really nice.
Then after a while, I could not receive anymore results. The script still ran, but no mp3 output from gTTS. 
After an investigation, I relieved that now I can only run gTTS from Python console called in Command Prompt, and I have to put each line of scripts into it. 
My Python version: 3.5
I'm using Spyder IDE 3.0.1
Windwos 10 64 bit

**Comment by sukhoi** [comment]
@tranquockhue please add some code!

**Comment by tranquockhue** [comment]
I used the default code. Maybe I spammed request :p Btw, now I can use it normally. 
Thank you
