### ISSUE TITLE
gTTS with raspberry pi

### ISSUE THREAD

**Issue by aylakadam** [pndurette/gTTS#53]
How install the raspberry pi?

**Comment by java2man** [comment]
I have installed on Raspberry Pi3 successfully just by "pip install gTTS".

**Comment by DefinitelyNotRoot** [comment]
Just do:
sudo pip3 (for python3) / pip (python2) install gTTS.
or you can always download and install newest version from github  
git clone https://github.com/pndurette/gTTS.git
cd gTTS
python3 or python setup.py install
