### ISSUE TITLE
Feature request - Translate

### ISSUE THREAD

**Issue by anoop1409** [pndurette/gTTS#55]
Not an issue but when  I saw the lang argument (text='text here', lang='hi'), I thought it would translate the text to the specified language and return back the output sound in the translated language. 

Is there a way we can achieve this? Just like the way it works here - https://translate.google.com

Thanks!

**Comment by pndurette** [comment]
Hi @anoop1409, a quick search on PyPI listed [plenty of libs that do this already!](https://pypi.python.org/pypi?%3Aaction=search&term=translate&submit=search), using Google, Bing or others. The goal of gTTS was purely to use the text-to-speech feature of Google Translate. The `lang` parameter is strictly for the voice/accent in this case.
