### ISSUE TITLE
add the Ukrainian language

### ISSUE THREAD

**Issue by bbs2009** [pndurette/gTTS#63]
Do you have the opportunity to add the Ukrainian language? He is present in the Google translation service. Thank you.

**Comment by pndurette** [comment]
Hi, yes! 👍
I'm currently reviewing all the available languages. I'm missing a few which will be added. 

--
Pierre Nick Durette

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released, adding this.
