### ISSUE TITLE
'pt' language speech isn´t portuguese native speech

### ISSUE THREAD

**Issue by danieloureiro** [pndurette/gTTS#66]
Hello,

I´ve tested pt and pt-br and the speech is always the same.
I attached two files one in 'pt' and another in 'pt-br' to check that is the same speech.
If you can help me I appreciate.

[lang.zip](https://github.com/pndurette/gTTS/files/919015/lang.zip)

**Comment by pndurette** [comment]
Thanks for that. I'm constrained to what Google gives me. It indeed sounds the same, so to avoid confusion and false expectations, I've removed `pt-br` from the list, kept `pt`. Will be in next release.

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released.
