### ISSUE TITLE
--slow option does not work

### ISSUE THREAD

**Issue by SamuelMiller** [pndurette/gTTS#67]
Hello,
When I run your example "gtts-cli.py "Hello" -l 'en' -o hello.mp3 -slow" in the terminal in Linuxmint 18.1 xfce, using the latest version through pip, I get the error:
"gtts-cli.py: error: unrecognized arguments: --slow"
Also, I would appreciate it if you could add a parameter to precisely adjust the speed of voice in the command line options (e.g., --speed 0.8)

**Comment by pndurette** [comment]
Ahh, it's not been released yet, apologies.
Doing this soon. Also as a note, I don't control the API just allow an interface to it. And there's only two voice speeds, normal and slow. 

--
Pierre Nick Durette

**Comment by pndurette** [comment]
Hi! [gTTS 1.20](https://pypi.python.org/pypi/gTTS/1.2.0) was released, adding this.

**Comment by SamuelMiller** [comment]
Thanks!
