### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by aalireza** [pndurette/gTTS#7]
Google asks for a captcha when I go to (translate.google.com/translate_tts?tl=en&q=Test) and gtts-cli produces an empty file. I've tried with different IPs and none of them work. Does gtts-cli still works properly?

**Comment by pndurette** [comment]
In it's current state it stopped yesterday— 😕
I've tried different user agents to no avail. I've been made aware of another project which uses this endpoint that apparently fixed it using some extra specific headers. I need to look at that ASAP. Thanks for opening the issue.

**Comment by pndurette** [comment]
Fixed it. Carved out release 1.0.6 on PyPi :+1: 
Thanks!

**Comment by aalireza** [comment]
Awesome!
