### ISSUE TITLE
Failed to load gTTS module

### ISSUE THREAD

**Issue by tangb** [pndurette/gTTS#72]
Hello

I'm using your module for sometime now and I just got an error importing gTTS module after aptitude update on a raspberry (jessie).
The urllib3 package is on version 1.9.1 (installed from apt not pip)
As I can see in your setup.py there is no dependency with urllib3, is it normal or an oversight?
Anyway the problem comes from InsercureRequestWarning that cannot be imported as it is in gTTS code.

Full exception trace:
>>> from gtts import gTTS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gtts/__init__.py", line 2, in <module>
    from .tts import gTTS
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 4, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning

Pip freeze:
alabaster==0.7.10
appdirs==1.4.3
argh==0.26.2
astral==1.4
Babel==2.4.0
backports-abc==0.5
bottle==0.12.7
certifi==2017.4.17
chardet==2.3.0
colorama==0.3.2
decorator==3.4.0
docutils==0.13.1
gevent==1.1.0
greenlet==0.4.12
gTTS==1.2.0
gTTS-token==1.1.1
html5lib==0.999
imagesize==0.7.1
Jinja2==2.9.6
livereload==2.5.1
Mako==1.0.6
Markdown==2.4.1
MarkupSafe==1.0
ndg-httpsclient==0.3.2
numpy==1.8.2
packaging==16.8
passlib==1.6.1
pathtools==0.1.2
pdoc==0.3.2
Pillow==2.6.1
pockets==0.5.1
port-for==0.3.1
psutil==2.1.1
pyasn1==0.1.7
pygame==1.9.2a0
Pygments==2.2.0
pyOpenSSL==0.13.1
pyparsing==2.2.0
python-apt==0.9.3.12
pytz==2017.2
PyYAML==3.12
requests==2.13.0
RPi.GPIO==0.6.3
scipy==0.14.0
simplejson==3.6.5
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.6
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.2.4
sphinxcontrib-napoleon==0.6.1
spidev==3.0
tornado==4.5.1
urllib3==1.21
watchdog==0.8.3
xmljson==0.1.8

A fix:
  4 #from requests.packages.urllib3.exceptions import InsecureRequestWarning
  5 import requests.packages.urllib3.exceptions as urllib3_exceptions
  6 from gtts_token.gtts_token import Token
134                 with warnings.catch_warnings():
135                     warnings.filterwarnings("ignore", category=urllib3_exceptions.InsecureRequestWarning)
136                     r = requests.get(self.GOOGLE_TTS_URL,

Thank you for your module it rocks :smile:

**Comment by abhi18av** [comment]
@wsngamerz , nope that doesn't clear out the problem.

**Comment by abhishekhandacse** [comment]
Very annoying error with probably no fix

Really Unfortunate... :-1:

**Comment by tangb** [comment]
For me it fixes the problem but it also breaks pip on system. Urllib developpers advice is to use virtual env to run gtts+request updated.

**Comment by pndurette** [comment]
Sorry for the delay on this.

Thanks @tangb!

> As I can see in your setup.py there is no dependency with urllib3, is it normal or an oversight?
I use what's in `requests` for this. I let it take care of it.

So as @tangb said, it's really better to run this in a sandboxed Python env (such as `virtualenv`). I do all my testing (and CI runs) in virtuenvs for both Python `2.x`s and `3.x`s and it's been fine.
