### ISSUE TITLE
Encoding error : Cannot handle more than 100 non-ascii characters.

### ISSUE THREAD

**Issue by XueWei** [pndurette/gTTS#73]
when use gTTS, pass in text more than 100 character, it report error:
"'utf8' codec can't decode byte 0xe8 in position 0: unexpected end of data". Test case:
text = "这是一个三岁的小孩
在讲述她从一系列照片里看到的东西。
对这个世界， 她也许还有很多要学的东西，
但在一个重要的任务上， 她已经是专家了：
去理解她所看到的东西。
 我们的社会已经在科技上取得了前所未有的进步。"
tts = gTTS(text=text, lang=args.lang)

**Comment by pndurette** [comment]
This should be fixed in `gTTS` v`1.2.1` that was just released. I used all the examples above for testing. It was an issue with Python 2.7. Let me know how it goes!
