### ISSUE TITLE
How to append to save mp3 file?

### ISSUE THREAD

**Issue by XueWei** [pndurette/gTTS#74]
Typical step to generate a speech file (mp3) from text is :

from gtts import gTTS
tts = gTTS(text='Hello', lang='en', slow=True)
tts.save("hello.mp3")

if I cannot give all text at once, how can I append to save mp3 file?
For example:
from gtts import gTTS
tts1 = gTTS(text='Hello', lang='en', slow=True)
tts2 = gTTS(text='World', lang='en', slow=True)

How to tts2 append to tts1 to write speech tts1 and tts2 into save file?

**Comment by pndurette** [comment]
Hi!

You can achieve this with the `write_to_fp()` method. It allows you to write to any file-like object and work with it until you close it. Here's a working example using your two `tts1` and `tts2` instances:

```python
from gtts import gTTS

tts1 = gTTS(text='Hello', lang='en', slow=True)
tts2 = gTTS(text='World', lang='en', slow=True)

with open('hello-world.mp3', 'w') as f:
    tts1.write_to_fp(f)
    tts2.write_to_fp(f)
```
