### ISSUE TITLE
'utf8' codec can't decode byte 0x8c in position 0: invalid start byte

### ISSUE THREAD

**Issue by 42RK** [pndurette/gTTS#76]
this happens when I try running gtts-cli.py -o polish.mp3 -f polish.txt -l pl
basically Polish characters seem not to be properly supported by the program

**Comment by pndurette** [comment]
@42RK Hi!
Make sure you run the latest version of (`gtts-cli --help`), should be `1.2.1` (asking since that version fixed similar issues).

If it still doesn't work, can you let me know the following?
- What version of Python are you using?
- What's the contents of `polish.txt` (so I can try it out)

Thanks!

**Comment by antares2001** [comment]
Hello,

I face the same error with the following text:

```
gtts-cli "Dies ist nun der zweite Text, der nicht während des ersten gesprochen werden sollte." -l 'de' -o /tmp/test.mp3 --debug
'ascii' codec can't decode byte 0xc3 in position 41: ordinal not in range(128)
```

I am using python on a Raspberry Pi 3:

```
$ python -V
Python 2.7.13

```

Thanks a lot for your review.

**Comment by pndurette** [comment]
@antares2001 Thanks for all the info. I'll have to take a look, but won't have time for at least two weeks unfortunately. It can be a real sport to keep everything happy unicode-wise on both Python 2.x and 3.x.

**Comment by antares2001** [comment]
I'm fine with 1.1.5 currently, so no worries. Take your time :)

**Comment by XueWei** [comment]
@pndurette Fixed by https://github.com/pndurette/gTTS/pull/78, please review and merge.

**Comment by XueWei** [comment]
@pndurette  Can you please take a look this PR https://github.com/pndurette/gTTS/pull/78

**Comment by luckytoilet** [comment]
I'm also having this issue. My Python version is 2.7.12, I'm running Ubuntu 16.04 in WSL. The problem only appears when I install using pip; if I clone this repo and run it, everything is fine.

**Comment by pndurette** [comment]
gTTS `2.0.0` was released and should fix this! 👍
