### ISSUE TITLE
I can't use Google API in China

### ISSUE THREAD

**Issue by Hwzsnow** [pndurette/gTTS#79]
Oh my god

**Comment by theawangatang** [comment]
Google is blocked by "Great Firewall" in China

**Comment by idiomer** [comment]
Hi, I use the code below. But I got something strange that the mp3 sounds like "a r".  How can I get the right sound?

`python -c "from gtts import gTTS; tts = gTTS(text=u'中文', lang='zh', slow=False); tts.save('hello.mp3')"`

**Comment by pndurette** [comment]
Yeah, there's nothing I can do about this, unfortunately. This library takes for granted it has access to the API.
