### ISSUE TITLE
gTTS speed

### ISSUE THREAD

**Issue by dirkjobosman** [pndurette/gTTS#84]
In the documentation it only mentions slow speed, is there a **medium** or a **fast** option as well ? Anything related to speed per second which one can set oneself would be super helpful. 

gtts-cli.py [-h] (["text to speak"] | -f FILE) [-l LANG] [--slow] [--debug] [-o destination_file]
$ # Read the string 'Hello' in English (slow speed) to hello.mp3
$ gtts-cli "Hello" -l 'en' -o hello.mp3 --slow

Thanks and thanks for this library!

**Comment by jelimoore** [comment]
Sorry to bump an old topic.

If you just don't specify --slow it should just speak it at normal speed.

**Comment by dirkjobosman** [comment]
Thanks a lot for the reply. Would be cool to document that to :)
