### ISSUE TITLE
How with google text-to-speech (gTTS) I can save to the MP3 file 2 Variables with different languages? (Python)

### ISSUE THREAD

**Issue by vladislav55** [pndurette/gTTS#90]
How with google text-to-speech I can save to the MP3 file 2 Variables with different languages? Please help me. Everywhere is written only for 1 language. This is my code:

```
from gtts import gTTS
import os
import pickle
import pandas as pd

frame = pd.read_csv('file.csv', header=0, sep = '\t', encoding='cp1251')
print(frame)

text1 = list()
text2 = list()

for a, b in zip(frame['English'], frame['Русский']):
    text1.append(a)
    text2.append(b)

print(text1,
      text2)

text1 = str(text1)
text2 = str(text2)

tts1 = gTTS(text=text1, lang='en')
tts2 = gTTS(text=text2, lang='ru')


# tts2.save("from_file.mp3") it work just for one Variable!



with open('from_file.mp3', 'wb') as pickle_file:
    pickle.dump([tts1, tts2], pickle_file) 
# with pickle it doesn't work!

os.system("from_file.mp3")
```

file content:

```
English   Русский

tell	  говорить
fly	  летать
sit	  сидеть
act	  действовать
```

As a solution: I can loop every word with gTTS and add in mp3 file, but how can I add data in mp3 without delete past data ?? I want to create an audio dictionary.

**Comment by cd412** [comment]
This should help you get two languages in one mp3 file.
```
from gtts import gTTS
import os
import pandas as pd

frame = pd.read_csv('file.csv', header=0, sep = '\t')
print(frame)

text1 = list()
text2 = list()

for a, b in zip(frame['English'], frame['Russian']):
    text1.append(a)
    text2.append(b)

print(text1,
      text2)

text1 = str(text1)
text2 = str(text2)

tts1 = gTTS(text=text1, lang='en')
tts2 = gTTS(text=text2, lang='ru')

with open('from_file.mp3', 'wb') as fp:
    tts1.write_to_fp(fp)
    tts2.write_to_fp(fp)    

os.system("from_file.mp3")

# file contents:
# English	Russian
# one		1	
# two		2
# three		3
# four		4

**Comment by ZHoscar** [comment]
I tried to implement the above solution but the write_to_fp function simply write in the first language!!
`
from gtts import gTTS
text1 = "this is english"
text2 = "這是中文"
tts1 = gTTS(text = text1, lang = 'en')
tts2 = gTTS(text = text2, lang ='zh-tw')

with open('File.mp3', 'wb') as fp:
    tts1.write_to_fp(fp)
    tts2.write_to_fp(fp) // this argument won't be written in fp
    tts1.write_to_fp(fp) // however this argument will 

`

How do I properly implement write_to_fp so that I could have file contain different languages?
Thank you!

**Comment by vladislav55** [comment]
You need to use **for** . You will have 1 mp3 file with this sequence of words --> 'en', 'zh-tw', 'en', 'zh-tw'....
"File.mp3" should be in the project directory or specify the full path to the file.

You can use tts1 = gTTS(text=t1, lang='en', **slow=True**)  if you want to play slowly.
You can also use Pandas if you wany to take the words from a file (.txt , .csv ......)

`from gtts import gTTS
import os
import pandas as pd

frame = pd.read_csv('file.csv', header=0, sep = '\t', encoding='cp1251')
print(frame)

text1 = list()
text2 = list()

for a, b in zip(frame['English'], frame['Русский']):
    text1.append(a)
    text2.append(b)

#print(text1, text2)

with open('from_file.mp3', 'wb') as fp:
    for t1, t2 in zip(text1, text2):
        t1 = str(t1)
        t2 = str(t2)
        #print(t1)
        #print(t2)
        q = gTTS(text=t1, lang='en')
        w = gTTS(text=t2, lang='ru')
        #print(q)
        #print(w)
        q.write_to_fp(fp)
        w.write_to_fp(fp)
 
os.system("from_file.mp3")`

**Comment by ZHoscar** [comment]
Hi thank you for the reply.
But is this code tested successfully?
Because when I tried on my local machine ( mac osx 10.13)

I am still getting one language as output.

```
text1 = list()
text2 = list()

text1.append('english')
text1.append('english as well')
text2.append('中文')
text2.append('也是中文')

with open ('file.mp3', 'wb') as fp:
    for t1, t2 in zip (text1, text2):
        t1 = str(t1)
        t2 = str(t2)
        print(t1)
        print(t2)
        q = gTTS(text=t1, lang= 'en')
        w = qTTS(text=t2, lang='zh-TW')

        q.write_to_fp(fp)
        w.write_to_fp(fp)

```

after playing file.mp3 the voice is 
english ,  english as well

There is no other languages in it.

**Comment by vladislav55** [comment]
You shoud be more attentive
`w = qTTS(text=t2, lang='zh-TW')`
correct code is:
`w = gTTS(text=t2, lang='zh-TW')`

This code is correct.
You can try another language.

The problem is **encoding** for chinese words and I don't know the solution relatively that.

**Comment by pndurette** [comment]
I just gave this a go, with the following changes (for Python 3):

```diff
+ from gtts import gTTS
text1 = list()
text2 = list()

text1.append('english')
text1.append('english as well')
text2.append('中文')
text2.append('也是中文')

with open ('file.mp3', 'wb') as fp:
    for t1, t2 in zip (text1, text2):
        t1 = str(t1)
        t2 = str(t2)
        print(t1)
        print(t2)
        q = gTTS(text=t1, lang= 'en')
-        w = qTTS(text=t2, lang='zh-TW')
+        w = gTTS(text=t2, lang='zh-TW')
        q.write_to_fp(fp)
        w.write_to_fp(fp)
```

And it works great.

If you're using Python 2.7, keep in mind that Unicode/Strings are handled differently:
* You must set the encoding of the file `# -*- coding: utf-8 -*-`
* You must write the Chinese characters as Unicode literals:
```
text2.append(u'中文')
text2.append(u'也是中文')
```
* You can't do `str()` on a Unicode without decoding it first. But you don't need to do that, `gTTS` handles it.

So, for Python 2, you'd do:
```diff
+ # -*- coding: utf-8 -*-
+ from gtts import gTTS

text1 = list()
text2 = list()

text1.append('english')
text1.append('english as well')
-text2.append(u'中文')
+text2.append(u'中文')
-text2.append(u'也是中文')
+text2.append(u'也是中文')

with open ('file.mp3', 'wb') as fp:
    for t1, t2 in zip (text1, text2):
-        t1 = str(t1)
-        t2 = str(t2)
        print(t1)
        print(t2)
        q = gTTS(text=t1, lang= 'en')
-        w = qTTS(text=t2, lang='zh-TW')
+        w = gTTS(text=t2, lang='zh-TW')

        q.write_to_fp(fp)
        w.write_to_fp(fp)
```

**Comment by Multibeam** [comment]
Hi, I also failed to combine Mandarin with other languages.
Please see following code:
```
# -*- coding: utf-8 -*-
from gtts import gTTS

lang_en = gTTS(text='hello', lang= 'en')
lang_ru = gTTS(text='Привет', lang='ru')
lang_fr = gTTS(text='bonjour', lang='fr')
lang_tw = gTTS(text=u'你好', lang='zh-TW')

with open ('file_1234.mp3', 'wb') as fp:   
    lang_en.write_to_fp(fp)
    lang_ru.write_to_fp(fp)
    lang_fr.write_to_fp(fp)
    lang_tw.write_to_fp(fp)

with open ('file_4321.mp3', 'wb') as fp:   
    lang_tw.write_to_fp(fp)
    lang_fr.write_to_fp(fp)
    lang_ru.write_to_fp(fp)
    lang_en.write_to_fp(fp)

with open ('file_12343.mp3', 'wb') as fp:   
    lang_en.write_to_fp(fp)
    lang_ru.write_to_fp(fp)
    lang_fr.write_to_fp(fp)
    lang_tw.write_to_fp(fp)
    lang_fr.write_to_fp(fp)
```
file_1234.mp3 outputs English, Russian, French
file_4321.mp3 outputs Mandarin only
file_12343.mp3 outputs English, Russian, French, French

Same result if replace "zh-tw" to "zh-cn"
