### ISSUE TITLE
codec can't decode byte 0xe3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by sydridgmLee** [pndurette/gTTS#93]
I can use follow command a few days ago, but today it doesn't work.

gtts-cli "こんにちは世界" -l 'ja' -o hello.mp3
'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)

gtts-cli -f 30cd06da-cd1c-45b6-724e-c5e03a65c335.txt -l 'ja' -o hello.mp3
No text to speak
//the file is in Japanese.

Testing the command in English works well.
Can you fix it.

**Comment by pndurette** [comment]
gTTS `2.0.0` was released and should fix this! 👍
