### ISSUE TITLE
Can't make mp3 file from the text in Romanian 

### ISSUE THREAD

**Issue by talnacialex** [pndurette/gTTS#96]
Hello! I am trying to run gTTS(latest version). I get this error:
(Bună ziua means in romanian "Good day!")
$ ~ gtts-cli "Bună ziua." -l 'ro' -o text.mp3
'ascii' codec can't decode byte 0xc4 in position 3: ordinal not in range(128)

Can you help me?

$ python --version
Python 2.7.13

$ gtts-cli --help
<usage>
Creates an mp3 file from spoken text via the Google Text-to-Speech API (1.2.3)
 
Have a nice day/night! We have a very big timezone difference.

**Comment by pndurette** [comment]
Hi, sorry about that. gTTS `2.0.0` is in the works with a re-written cli that will handle Unicode much better in Python 2 and 3. Expect that soon.

**Comment by talnacialex** [comment]
Ok! In the meantime, I made something similar to gTTS and now it works. I used the gtts-token(yes, cheating, i know) library in Python, then I made requests and downloaded the wave... Now it works... Thank you for your help! You can mark this now as solved.
